# TODO (if we can)
# - Label PRs in need of codeowner review
# - viz:charts:xyz labels
# – component/design system areas
# - storybook(s)
# - f/e and b/e test changes?
# - product areas (SQL Lab, Explore, Dashboard, etc.)
# - database areas (SQLAlchemy, labelind DBs by driver, etc.)

############################################
# General workflow warnings
# full list of labels is here: https://github.com/defai-digital/ax-bi/labels
############################################

"risk:db-migration":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/migrations/**'

"risk:ci-script":
- changed-files:
  - any-glob-to-any-file:
    - 'scripts/**'

############################################
# Dependencies
############################################

"dependencies:python":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/requirements/**'
    - 'axbi/translations/requirements.txt'

"dependencies:npm":
- changed-files:
  - any-glob-to-any-file:
    - 'ax-bi-frontend/package.json'
    - 'ax-bi-frontend/package-lock.json'
    - 'ax-bi-embedded-sdk/package.json'
    - 'ax-bi-embedded-sdk/package-lock.json'
    - 'ax-bi-websocket/package.json'
    - 'ax-bi-websocket/package-lock.json'
    - 'ax-bi-frontend/cypress-base/package.json'
    - 'ax-bi-frontend/cypress-base/package-lock.json'
    - 'ax-bi-frontend/packages/**/package.json'
    - 'ax-bi-frontend/plugins/**/package.json'

############################################
# Areas of the main codebase
############################################

"doc":
- changed-files:
  - any-glob-to-any-file:
    - 'docs/**'

"api":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/**/api.py'
    - 'axbi/views/core.py'

"i18n":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/**'

"i18n:brazilian":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/pt_BR/**'

"i18n:chinese":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/zh/**'

"i18n:czech":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/cs/**'

"i18n:traditional-chinese":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/zh_TW/**'

"i18n:dutch":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/nl/**'

"i18n:french":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/fr/**'

"i18n:italian":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/it/**'

"i18n:japanese":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/ja/**'

"i18n:korean":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/ko/**'

"i18n:portuguese":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/pt/**'

"i18n:russian":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/ru/**'

"i18n:slovak":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/sk/**'

"i18n:latvian":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/lv/**'

"i18n:ukrainian":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/uk/**'

"i18n:spanish":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/es/**'

"i18n:persian":
- changed-files:
  - any-glob-to-any-file:
    - 'axbi/translations/fa/**'

############################################
# Sub-projects and monorepo packages
############################################

"plugins":
- changed-files:
  - any-glob-to-any-file:
    - 'ax-bi-frontend/plugins/**'

"packages":
- changed-files:
  - any-glob-to-any-file:
    - 'ax-bi-frontend/packages/**'

"embedded":
- changed-files:
  - any-glob-to-any-file:
    - 'ax-bi-embedded-sdk/**'

"github_actions":
- changed-files:
  - any-glob-to-any-file:
    - '.github/actions/**'
    - '.github/workflows/**'
