// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! App-managed local AX BI runtime.
//!
//! Platform engines:
//! - **macOS:** isolated Colima profile `ax-bi` (needs Lima / `limactl` on PATH)
//! - **Windows / Linux:** host Docker Engine (typically Docker Desktop)
//!
//! Compose stack and ports are identical across platforms. GUI-launched apps
//! often lack Homebrew/Docker bins on `PATH`; every subprocess gets an
//! augmented PATH so `colima` can find `limactl` and Docker CLIs resolve.

use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::ffi::OsStr;
use std::fs;
use std::io::{Read, Write};
use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::mpsc;
use std::sync::OnceLock;
use std::thread;
use std::time::{Duration, Instant};
use tauri::{AppHandle, Manager, Runtime};

const AXBI_COLIMA_PROFILE: &str = "ax-bi";
const COLIMA_PROFILE_ENV: &str = "COLIMA_PROFILE";
const AXBI_COMPOSE_PROJECT: &str = "axbi";
const AXBI_ADMIN_USERNAME: &str = "admin";
const AXBI_HEALTH_HOST: &str = "127.0.0.1";
const AXBI_HEALTH_PORT: u16 = 31423;
const AXBI_MCP_PORT: u16 = 31421;
const AXBI_SERVICES_PORT: u16 = 31424;
const AXBI_COLIMA_CPUS: &str = "4";
const AXBI_COLIMA_MEMORY_GB: &str = "8";
/// Hard ceiling for docker/colima/netstat subprocesses so hung daemons cannot
/// pin the desktop process forever.
const COMMAND_TIMEOUT: Duration = Duration::from_secs(300);
const MANAGED_AXBI_IMAGE_REPO: &str = "ghcr.io/defai-digital/ax-bi";
const MANAGED_AX_SERVICES_IMAGE_REPO: &str = "ghcr.io/defai-digital/ax-bi-services";
const AXBI_DESKTOP_VERSION_ENV: &str = "AXBI_DESKTOP_VERSION";
const AXBI_IMAGE_ENV: &str = "AXBI_IMAGE";
const AX_SERVICES_IMAGE_ENV: &str = "AX_SERVICES_IMAGE";
const STARTUP_HEALTH_RECONCILE_WAIT: Duration = Duration::from_secs(120);
const STARTUP_HEALTH_RECONCILE_POLL: Duration = Duration::from_secs(2);
const COMPOSE_FAILURE_RECONCILE_WAIT: Duration = Duration::from_secs(10);
const LOCAL_RUNTIME_DIR: &str = "local-runtime";
const LOCAL_ENV_FILE: &str = ".env";
const LOCAL_COMPOSE_FILE: &str = "docker-compose.yml";
const LOCAL_ONBOARDING_COMPLETE_FILE: &str = ".admin-onboarding-complete";
const MAX_LOG_TAIL_LINES: u16 = 500;
const DOCKER_ENGINE_WAIT: Duration = Duration::from_secs(120);
const DOCKER_ENGINE_POLL: Duration = Duration::from_secs(2);
static LOCAL_RUNTIME_DEPENDENCIES: OnceLock<Vec<LocalRuntimeDependency>> = OnceLock::new();

const ALLOWED_LOG_SERVICES: &[&str] = &[
    "redis",
    "db",
    "ax-bi-init",
    "ax-bi",
    "ax-bi-worker",
    "ax-bi-worker-beat",
    "mcp",
    "ax-services",
];

const LOCAL_COMPOSE_YAML: &str = r#"# Generated by AX BI Desktop.
# This file is managed by the desktop local runtime manager.

x-axbi-image: &axbi-image ${AXBI_IMAGE:?Set AXBI_IMAGE in .env}
x-axbi-services-image: &axbi-services-image ${AX_SERVICES_IMAGE:?Set AX_SERVICES_IMAGE in .env}

x-axbi-env: &axbi-env
  AXBI_CONFIG_PATH: /app/docker/pythonpath_axbi/axbi_config.py
  AXBI_ENV: production
  AXBI_LOAD_EXAMPLES: ${AXBI_LOAD_EXAMPLES:-no}
  AXBI_LOG_LEVEL: ${AXBI_LOG_LEVEL:-info}
  AXBI_PORT: 31423
  AX_BI_SECRET_KEY: ${AX_BI_SECRET_KEY:?Set AX_BI_SECRET_KEY in .env}
  AX_SERVICES_BASE_URL: http://ax-services:31424
  AX_SERVICES_INTERNAL_TOKEN: ${AX_SERVICES_INTERNAL_TOKEN:?Set AX_SERVICES_INTERNAL_TOKEN in .env}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD in .env}
  DATABASE_DIALECT: ${DATABASE_DIALECT:-postgresql}
  DATABASE_HOST: ${DATABASE_HOST:-db}
  DATABASE_PORT: ${DATABASE_PORT:-5432}
  DATABASE_DB: ${DATABASE_DB:-axbi}
  DATABASE_USER: ${DATABASE_USER:-axbi}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:?Set DATABASE_PASSWORD in .env}
  UPLOAD_FOLDER: ${UPLOAD_FOLDER:-/app/axbi_home/uploads}
  LOCAL_DB_NAME: ${LOCAL_DB_NAME:-Local Files}
  LOCAL_DB_PATH: ${LOCAL_DB_PATH:-/app/axbi_home/uploads/local_files.duckdb}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  ENABLE_PROXY_FIX: ${ENABLE_PROXY_FIX:-true}
  SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-false}
  TALISMAN_ENABLED: ${TALISMAN_ENABLED:-false}
  MCP_AUTH_ENABLED: ${MCP_AUTH_ENABLED:-false}
  MCP_DEV_USERNAME: ${MCP_DEV_USERNAME:-admin}
  MCP_JWT_ISSUER: ${MCP_JWT_ISSUER:-}
  MCP_JWT_AUDIENCE: ${MCP_JWT_AUDIENCE:-}
  MCP_JWKS_URI: ${MCP_JWKS_URI:-}
  MCP_REQUIRED_SCOPES: ${MCP_REQUIRED_SCOPES:-}
  GENAI_SEMANTIC_INDEX: ${GENAI_SEMANTIC_INDEX:-false}
  GENAI_SEMANTIC_INDEX_PGVECTOR: ${GENAI_SEMANTIC_INDEX_PGVECTOR:-false}
  AI_SEMANTIC_EMBEDDING_PROVIDER: ${AI_SEMANTIC_EMBEDDING_PROVIDER:-ax_engine_http}
  AI_SEMANTIC_EMBEDDING_ENDPOINT: ${AI_SEMANTIC_EMBEDDING_ENDPOINT:-http://host.docker.internal:8099/embed}
  AI_SEMANTIC_EMBEDDING_MODEL: ${AI_SEMANTIC_EMBEDDING_MODEL:-Qwen/Qwen3-Embedding-0.6B}
  AI_SEMANTIC_EMBEDDING_DIMENSIONS: ${AI_SEMANTIC_EMBEDDING_DIMENSIONS:-1024}

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg18}
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB:-axbi}
      POSTGRES_USER: ${POSTGRES_USER:-axbi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?Set DATABASE_PASSWORD in .env}
    volumes:
      - db_home:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-axbi} -d ${POSTGRES_DB:-axbi}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  ax-bi-init:
    image: *axbi-image
    command: ["/app/docker/docker-init.sh"]
    environment: *axbi-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - axbi_home:/app/axbi_home
    healthcheck:
      disable: true

  ax-bi:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:${AXBI_PORT:-31423}:31423"
    environment: *axbi-env
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "/app/docker/docker-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-bi-worker:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: unless-stopped
    environment: *axbi-env
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A axbi.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-bi-worker-beat:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: unless-stopped
    environment: *axbi-env
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    healthcheck:
      disable: true

  mcp:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "mcp"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MCP_PORT:-31421}:31421"
    environment:
      <<: *axbi-env
      MCP_PORT: 31421
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import socket; socket.create_connection(('127.0.0.1', 31421), 5).close()",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-services:
    image: *axbi-services-image
    restart: unless-stopped
    environment:
      AX_SERVICES_HOST: 0.0.0.0
      AX_SERVICES_PORT: 31424
      AXBI_BASE_URL: http://ax-bi:31423
      AX_SERVICES_INTERNAL_TOKEN: ${AX_SERVICES_INTERNAL_TOKEN:?Set AX_SERVICES_INTERNAL_TOKEN in .env}
      AX_SERVICES_LOG_LEVEL: ${AX_SERVICES_LOG_LEVEL:-info}
    ports:
      - "127.0.0.1:${AX_SERVICES_PORT:-31424}:31424"
    depends_on:
      ax-bi:
        condition: service_healthy

volumes:
  axbi_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeDependency {
    pub name: String,
    pub command: String,
    pub resolved_path: String,
    pub installed: bool,
    pub version: Option<String>,
    pub install_hint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimePort {
    pub name: String,
    pub port: u16,
    pub url: String,
    pub available: bool,
    pub occupied_by_axbi: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeStatus {
    pub runtime_dir: String,
    pub compose_file: String,
    pub env_file: String,
    pub configured: bool,
    pub dependencies: Vec<LocalRuntimeDependency>,
    pub ports: Vec<LocalRuntimePort>,
    /// OS label: `macos`, `windows`, or `linux`.
    pub platform: String,
    /// Always true on desktop builds — both macOS and Windows can run local AX BI Docker.
    pub local_runtime_supported: bool,
    /// True when required CLI tools are installed (engine may still need to start).
    pub can_start_local: bool,
    /// Engine identifier: `colima` (macOS) or `docker` (Windows/Linux).
    pub engine_name: String,
    /// UI label for the VM/engine layer (e.g. "Colima", "Docker Engine").
    pub engine_label: String,
    /// Whether the container engine is ready enough to run Compose.
    pub engine_running: bool,
    /// Colima profile name on macOS; empty on other platforms.
    pub colima_profile: String,
    /// Backward-compatible alias of engine readiness for Colima-era clients.
    pub colima_running: bool,
    pub docker_host: String,
    pub docker_ready: bool,
    /// Whether any service in the managed Compose project is running.
    pub stack_running: bool,
    /// Whether the managed AX BI web service is running.
    pub axbi_running: bool,
    pub axbi_healthy: bool,
    pub web_url: String,
    pub mcp_url: String,
    pub services_url: String,
    pub admin_username: String,
    pub admin_password_present: bool,
    pub onboarding_required: bool,
    /// Desktop package version (`CARGO_PKG_VERSION`).
    pub desktop_version: String,
    /// Configured AX BI container image (from managed `.env` when present).
    pub axbi_image: String,
    /// Configured AX Services container image (from managed `.env` when present).
    pub ax_services_image: String,
    /// Recommended engine CPUs for local mode (Colima profile / host guidance).
    pub recommended_cpus: u16,
    /// Recommended engine memory in GiB for local mode.
    pub recommended_memory_gb: u16,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeCommandOutput {
    pub status: LocalRuntimeStatus,
    pub stdout: String,
    pub stderr: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalAdminCredentials {
    pub username: String,
    pub password: String,
}

#[derive(Debug)]
struct CommandOutput {
    stdout: String,
    stderr: String,
}

#[derive(Debug, Clone)]
struct RuntimeUrls {
    web_port: u16,
    mcp_port: u16,
    services_port: u16,
    web_url: String,
    mcp_url: String,
    services_url: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RuntimeEngine {
    Colima,
    Docker,
}

impl RuntimeEngine {
    fn current() -> Self {
        if cfg!(target_os = "macos") {
            Self::Colima
        } else {
            Self::Docker
        }
    }

    fn name(self) -> &'static str {
        match self {
            Self::Colima => "colima",
            Self::Docker => "docker",
        }
    }

    fn label(self) -> &'static str {
        match self {
            Self::Colima => "Colima",
            Self::Docker => "Docker Engine",
        }
    }
}

pub fn status<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeStatus, String> {
    log::info!("Checking local AX BI runtime status");
    let runtime_dir = runtime_dir(app)?;
    let compose_file = compose_file(&runtime_dir);
    let env_file = env_file(&runtime_dir);
    log::info!("Reading local runtime dependencies");
    let dependencies = dependencies();
    let urls = runtime_urls(&env_file);
    // Status is intentionally read-only: never rewrite compose/.env here.
    // Mutations happen in prepare/start/restart/update via ensure_runtime_files.
    let configured = compose_file.exists() && env_file.exists();

    let engine = RuntimeEngine::current();
    let colima_profile = configured_colima_profile(&env_file);
    let docker_host = docker_host(&colima_profile)?;
    log::info!("Checking Docker status");
    let docker_ready = docker_daemon_ready(&docker_host);
    // The managed Docker endpoint is the useful engine-readiness signal. A
    // Colima status call can take several seconds even when its daemon is ready.
    let engine_running = docker_ready;
    log::info!("Checking Compose service status");
    let running_services = if docker_ready {
        compose_running_services(&runtime_dir)?
    } else {
        HashSet::new()
    };
    let stack_running = !running_services.is_empty();
    let axbi_running = running_services.contains("ax-bi");
    let ports = local_runtime_ports(&urls, &running_services);
    log::info!("Checking AX BI HTTP health");
    let axbi_healthy = axbi_running && local_http_healthcheck(urls.web_port);
    let admin_password_present = configured
        && read_env_value(&env_file, "ADMIN_PASSWORD")
            .ok()
            .flatten()
            .map(|password| !password.is_empty())
            .unwrap_or(false);
    let onboarding_required =
        admin_password_present && !onboarding_complete_file(&runtime_dir).exists();

    let colima_profile = match engine {
        RuntimeEngine::Colima => colima_profile,
        RuntimeEngine::Docker => String::new(),
    };
    let can_start_local = dependencies.iter().all(|dependency| dependency.installed);
    let axbi_image = if configured {
        read_env_value(&env_file, AXBI_IMAGE_ENV)?
            .filter(|value| !value.is_empty())
            .unwrap_or_else(default_axbi_image)
    } else {
        default_axbi_image()
    };
    let ax_services_image = if configured {
        read_env_value(&env_file, AX_SERVICES_IMAGE_ENV)?
            .filter(|value| !value.is_empty())
            .unwrap_or_else(default_ax_services_image)
    } else {
        default_ax_services_image()
    };

    Ok(LocalRuntimeStatus {
        runtime_dir: path_to_string(&runtime_dir),
        compose_file: path_to_string(&compose_file),
        env_file: path_to_string(&env_file),
        configured,
        dependencies,
        ports,
        platform: platform_id().to_string(),
        local_runtime_supported: true,
        can_start_local,
        engine_name: engine.name().to_string(),
        engine_label: engine.label().to_string(),
        engine_running,
        colima_profile,
        // Keep Colima-era field name; UI uses engine_running / engine_label.
        colima_running: engine_running,
        docker_host,
        docker_ready,
        stack_running,
        axbi_running,
        axbi_healthy,
        web_url: urls.web_url,
        mcp_url: urls.mcp_url,
        services_url: urls.services_url,
        admin_username: AXBI_ADMIN_USERNAME.to_string(),
        admin_password_present,
        onboarding_required,
        desktop_version: desktop_version().to_string(),
        axbi_image,
        ax_services_image,
        recommended_cpus: AXBI_COLIMA_CPUS.parse().unwrap_or(4),
        recommended_memory_gb: AXBI_COLIMA_MEMORY_GB.parse().unwrap_or(8),
    })
}

/// Return the configured local web URL after a lightweight health validation.
///
/// The caller is already restricted to the bundled launcher, and the target
/// window has no local-runtime command privileges. Avoiding a second full
/// status scan keeps the launcher-to-web handoff responsive.
pub fn healthy_web_url<R: Runtime>(app: &AppHandle<R>) -> Result<String, String> {
    let runtime_dir = runtime_dir(app)?;
    let compose_path = compose_file(&runtime_dir);
    let env_path = env_file(&runtime_dir);
    if !compose_path.exists() || !env_path.exists() {
        return Err("Local AX BI runtime is not configured".to_string());
    }

    if !compose_running_services(&runtime_dir)?.contains("ax-bi") {
        return Err("The managed local AX BI web service is not running".to_string());
    }
    let urls = runtime_urls(&env_path);
    if !local_http_healthcheck(urls.web_port) {
        return Err("Local AX BI is not healthy yet".to_string());
    }
    Ok(urls.web_url)
}

pub fn prepare<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeStatus, String> {
    ensure_runtime_files(app)?;
    status(app)
}

pub fn start<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    ensure_cli_dependencies()?;
    ensure_required_ports_available(&runtime_dir)?;
    let engine_output = ensure_engine(&runtime_dir)?;
    let compose_output = start_compose_stack(&runtime_dir)?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(&engine_output.stdout, &compose_output.stdout),
        stderr: join_outputs(&engine_output.stderr, &compose_output.stderr),
    })
}

pub fn stop<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    // Stop should still try even if the engine is flaky; surface compose errors clearly.
    let output = run_docker_compose(&runtime_dir, &["stop"])
        .map_err(|error| format_compose_error("stop", &error, Some(&runtime_dir)))?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: output.stdout,
        stderr: output.stderr,
    })
}

pub fn restart<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    ensure_cli_dependencies()?;
    let engine_output = ensure_engine(&runtime_dir)?;
    let stop_output = run_docker_compose(&runtime_dir, &["stop"])
        .map_err(|error| format_compose_error("stop", &error, Some(&runtime_dir)))?;
    ensure_required_ports_available(&runtime_dir)?;
    let start_output = start_compose_stack(&runtime_dir)?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(
            &join_outputs(&engine_output.stdout, &stop_output.stdout),
            &start_output.stdout,
        ),
        stderr: join_outputs(
            &join_outputs(&engine_output.stderr, &stop_output.stderr),
            &start_output.stderr,
        ),
    })
}

pub fn update<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    ensure_cli_dependencies()?;
    let engine_output = ensure_engine(&runtime_dir)?;
    ensure_required_ports_available(&runtime_dir)?;
    let pull_output = run_docker_compose(&runtime_dir, &["pull"])
        .map_err(|error| format_compose_error("pull", &error, Some(&runtime_dir)))?;
    let start_output = start_compose_stack(&runtime_dir)?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(
            &join_outputs(&engine_output.stdout, &pull_output.stdout),
            &start_output.stdout,
        ),
        stderr: join_outputs(
            &join_outputs(&engine_output.stderr, &pull_output.stderr),
            &start_output.stderr,
        ),
    })
}

pub fn logs<R: Runtime>(
    app: &AppHandle<R>,
    service: Option<String>,
    tail: Option<u16>,
) -> Result<String, String> {
    let runtime_dir = runtime_dir(app)?;
    if !compose_file(&runtime_dir).exists() || !env_file(&runtime_dir).exists() {
        return Err("Local AX BI runtime has not been prepared".to_string());
    }

    let mut args = vec![
        "logs".to_string(),
        "--no-color".to_string(),
        "--tail".to_string(),
        tail_lines(tail).to_string(),
    ];
    if let Some(service_name) = service {
        let service_name = validate_log_service(&service_name)?;
        args.push(service_name.to_string());
    }

    let output = run_docker_compose_owned(&runtime_dir, args)?;
    Ok(join_outputs(&output.stdout, &output.stderr))
}

pub fn credentials<R: Runtime>(app: &AppHandle<R>) -> Result<LocalAdminCredentials, String> {
    let env_file = env_file(&runtime_dir(app)?);
    let password = read_env_value(&env_file, "ADMIN_PASSWORD")?
        .filter(|value| !value.is_empty())
        .ok_or_else(|| {
            "Local admin credentials are not available; prepare the runtime first".to_string()
        })?;

    Ok(LocalAdminCredentials {
        username: AXBI_ADMIN_USERNAME.to_string(),
        password,
    })
}

pub fn complete_admin_onboarding<R: Runtime>(app: &AppHandle<R>) -> Result<(), String> {
    let runtime_dir = runtime_dir(app)?;
    let env_path = env_file(&runtime_dir);
    let password_present = read_env_value(&env_path, "ADMIN_PASSWORD")?
        .map(|value| !value.is_empty())
        .unwrap_or(false);
    if !password_present {
        return Err(
            "Local admin credentials are not available; prepare the runtime first".to_string(),
        );
    }

    fs::write(onboarding_complete_file(&runtime_dir), "complete\n")
        .map_err(|error| format!("Failed to save local admin onboarding state: {error}"))
}

fn ensure_runtime_files<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    let runtime_dir = runtime_dir(app)?;
    fs::create_dir_all(&runtime_dir)
        .map_err(|error| format!("Failed to create local runtime directory: {error}"))?;

    let compose_path = compose_file(&runtime_dir);
    let env_path = env_file(&runtime_dir);
    sync_runtime_files(&compose_path, &env_path)?;

    Ok(runtime_dir)
}

fn sync_runtime_files(compose_path: &Path, env_path: &Path) -> Result<(), String> {
    write_file_if_changed(compose_path, LOCAL_COMPOSE_YAML, "local Compose file")?;

    if !env_path.exists() {
        write_runtime_env(env_path, &build_env_file()?)?;
    } else {
        ensure_runtime_secrets(env_path)?;
        ensure_managed_image_tags(env_path)?;
        ensure_colima_profile(env_path, compose_path)?;
        secure_runtime_env_permissions(env_path)?;
    }

    Ok(())
}

/// Write `content` only when the on-disk bytes differ, via temp file + rename.
fn write_file_if_changed(path: &Path, content: &str, label: &str) -> Result<(), String> {
    if path.exists() {
        match fs::read_to_string(path) {
            Ok(existing) if existing == content => return Ok(()),
            Ok(_) | Err(_) => {}
        }
    }

    atomic_write(path, content, label)
}

/// Atomically replace `path` with `content` (write temp sibling, then rename).
fn atomic_write(path: &Path, content: &str, label: &str) -> Result<(), String> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)
        .map_err(|error| format!("Failed to create parent for {label}: {error}"))?;

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("runtime.tmp");
    let temp_path = parent.join(format!(
        ".{file_name}.{}.tmp",
        std::process::id()
    ));

    let write_result = (|| {
        fs::write(&temp_path, content)
            .map_err(|error| format!("Failed to write temporary {label}: {error}"))?;
        fs::rename(&temp_path, path)
            .map_err(|error| format!("Failed to publish {label}: {error}"))?;
        Ok(())
    })();

    if write_result.is_err() {
        let _ = fs::remove_file(&temp_path);
    }
    write_result
}

fn runtime_dir<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|path| path.join(LOCAL_RUNTIME_DIR))
        .map_err(|error| format!("Failed to resolve app data directory: {error}"))
}

fn compose_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_COMPOSE_FILE)
}

fn env_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_ENV_FILE)
}

fn onboarding_complete_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_ONBOARDING_COMPLETE_FILE)
}

fn desktop_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Image tag used for managed desktop runtimes.
///
/// Release builds pin to the desktop package version so local stacks track the
/// release train. Debug builds keep `latest` so developers are not blocked when
/// GHCR has not published a matching version tag yet.
fn managed_image_tag() -> &'static str {
    if cfg!(debug_assertions) {
        "latest"
    } else {
        env!("CARGO_PKG_VERSION")
    }
}

fn default_axbi_image() -> String {
    format!("{MANAGED_AXBI_IMAGE_REPO}:{}", managed_image_tag())
}

fn default_ax_services_image() -> String {
    format!("{MANAGED_AX_SERVICES_IMAGE_REPO}:{}", managed_image_tag())
}

/// True when `image` is a DEFAI-managed registry ref we are allowed to re-pin.
fn is_managed_image_ref(image: &str, repo: &str) -> bool {
    let image = image.trim();
    if image.is_empty() {
        return true;
    }
    if image == repo {
        return true;
    }
    let prefix = format!("{repo}:");
    if let Some(tag) = image.strip_prefix(&prefix) {
        // Digests (`repo@sha256:…`) are treated as custom pins.
        return !tag.is_empty() && !image.contains('@');
    }
    false
}

fn build_env_file() -> Result<String, String> {
    let axbi_secret_key = random_hex(48)?;
    let database_password = random_hex(32)?;
    let admin_password = random_hex(18)?;
    let services_internal_token = random_hex(32)?;
    let axbi_image = default_axbi_image();
    let ax_services_image = default_ax_services_image();
    let desktop_version = desktop_version();

    Ok(format!(
        r#"COMPOSE_PROJECT_NAME={AXBI_COMPOSE_PROJECT}

AX_BI_SECRET_KEY={axbi_secret_key}
AX_SERVICES_INTERNAL_TOKEN={services_internal_token}
DATABASE_PASSWORD={database_password}
ADMIN_PASSWORD={admin_password}
COLIMA_PROFILE={AXBI_COLIMA_PROFILE}
{AXBI_DESKTOP_VERSION_ENV}={desktop_version}

{AXBI_IMAGE_ENV}={axbi_image}
{AX_SERVICES_IMAGE_ENV}={ax_services_image}
POSTGRES_IMAGE=pgvector/pgvector:pg18

AXBI_PORT=31423
MCP_PORT=31421
AX_SERVICES_PORT=31424

DATABASE_DB=axbi
DATABASE_USER=axbi
DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_DIALECT=postgresql
POSTGRES_DB=axbi
POSTGRES_USER=axbi

UPLOAD_FOLDER=/app/axbi_home/uploads
LOCAL_DB_NAME=Local Files
LOCAL_DB_PATH=/app/axbi_home/uploads/local_files.duckdb

AXBI_LOAD_EXAMPLES=no
AXBI_LOG_LEVEL=info
ENABLE_PROXY_FIX=true
SESSION_COOKIE_SECURE=false
TALISMAN_ENABLED=false

GENAI_SEMANTIC_INDEX=false
GENAI_SEMANTIC_INDEX_PGVECTOR=false
AI_SEMANTIC_EMBEDDING_PROVIDER=ax_engine_http
AI_SEMANTIC_EMBEDDING_ENDPOINT=http://host.docker.internal:8099/embed
AI_SEMANTIC_EMBEDDING_MODEL=Qwen/Qwen3-Embedding-0.6B
AI_SEMANTIC_EMBEDDING_DIMENSIONS=1024
AI_SEMANTIC_EMBEDDING_TIMEOUT=120

MCP_DEV_USERNAME={AXBI_ADMIN_USERNAME}
MCP_AUTH_ENABLED=false
MCP_JWT_ISSUER=
MCP_JWT_AUDIENCE=
MCP_JWKS_URI=
MCP_REQUIRED_SCOPES=
"#,
    ))
}

/// Write the generated runtime environment and restrict access to its secrets.
fn write_runtime_env(path: &Path, content: &str) -> Result<(), String> {
    atomic_write(path, content, "local runtime environment")?;
    secure_runtime_env_permissions(path)
}

/// Limit the runtime environment to its owning user.
fn secure_runtime_env_permissions(path: &Path) -> Result<(), String> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        fs::set_permissions(path, fs::Permissions::from_mode(0o600)).map_err(|error| {
            format!("Failed to secure local runtime environment permissions: {error}")
        })?;
    }

    #[cfg(windows)]
    {
        secure_runtime_env_permissions_windows(path)?;
    }

    let _ = path;
    Ok(())
}

#[cfg(windows)]
fn secure_runtime_env_permissions_windows(path: &Path) -> Result<(), String> {
    let path_str = path
        .to_str()
        .ok_or_else(|| "Local runtime environment path is not valid UTF-8".to_string())?;

    // Reset inheritance and grant only the current user full control.
    let reset = Command::new("icacls")
        .args([path_str, "/inheritance:r"])
        .output()
        .map_err(|error| format!("Failed to start icacls for runtime env: {error}"))?;
    if !reset.status.success() {
        return Err(format!(
            "Failed to reset ACLs on local runtime environment: {}",
            String::from_utf8_lossy(&reset.stderr)
        ));
    }

    let username = std::env::var("USERNAME").map_err(|_| {
        "USERNAME environment variable is unset; cannot restrict runtime env ACLs on Windows"
            .to_string()
    })?;
    if username.trim().is_empty() || username.contains('%') {
        return Err(
            "USERNAME environment variable is invalid; cannot restrict runtime env ACLs on Windows"
                .to_string(),
        );
    }
    let grant = format!("{username}:F");
    let grant_out = Command::new("icacls")
        .args([path_str, "/grant:r", &grant])
        .output()
        .map_err(|error| format!("Failed to start icacls grant for runtime env: {error}"))?;
    if !grant_out.status.success() {
        return Err(format!(
            "Failed to restrict local runtime environment to the current user: {}",
            String::from_utf8_lossy(&grant_out.stderr)
        ));
    }
    Ok(())
}

/// Add or repair generated secrets in an existing runtime environment.
fn ensure_runtime_secrets(path: &Path) -> Result<(), String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    if let Some(updated) = ensure_runtime_secrets_content(&content)? {
        write_runtime_env(path, &updated)?;
    }
    Ok(())
}

/// Return migrated environment content when any required secret needs repair.
fn ensure_runtime_secrets_content(content: &str) -> Result<Option<String>, String> {
    let mut updated = content.to_string();
    let mut changed = false;
    for (key, byte_count) in [("AX_BI_SECRET_KEY", 48), ("AX_SERVICES_INTERNAL_TOKEN", 32)] {
        if let Some(next) = ensure_generated_secret_content(&updated, key, byte_count)? {
            updated = next;
            changed = true;
        }
    }
    Ok(changed.then_some(updated))
}

/// Ensure one environment key has exactly one non-empty generated value.
fn ensure_generated_secret_content(
    content: &str,
    key: &str,
    byte_count: usize,
) -> Result<Option<String>, String> {
    let matching_lines = content
        .lines()
        .filter(|line| {
            line.split_once('=')
                .map(|(line_key, _)| line_key.trim() == key)
                .unwrap_or(false)
        })
        .count();
    let existing = content.lines().find_map(|line| {
        let (line_key, value) = line.split_once('=')?;
        (line_key.trim() == key && !value.trim().is_empty()).then(|| value.trim().to_string())
    });
    if matching_lines == 1 && existing.is_some() {
        return Ok(None);
    }

    let value = match existing {
        Some(value) => value,
        None => random_hex(byte_count)?,
    };
    let mut lines: Vec<&str> = content
        .lines()
        .filter(|line| {
            !line
                .split_once('=')
                .map(|(line_key, _)| line_key.trim() == key)
                .unwrap_or(false)
        })
        .collect();
    while lines.last().is_some_and(|line| line.trim().is_empty()) {
        lines.pop();
    }

    let mut updated = lines.join("\n");
    if !updated.is_empty() {
        updated.push('\n');
    }
    updated.push_str(&format!("{key}={value}\n"));
    Ok(Some(updated))
}

/// Keep managed image tags and desktop version aligned with this app release.
fn ensure_managed_image_tags(path: &Path) -> Result<(), String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    if let Some(updated) = ensure_managed_image_tags_content(&content) {
        write_runtime_env(path, &updated)?;
    }
    Ok(())
}

/// Rewrite managed image tags in `.env` content when they are still under DEFAI control.
fn ensure_managed_image_tags_content(content: &str) -> Option<String> {
    let desired_axbi = default_axbi_image();
    let desired_services = default_ax_services_image();
    let desired_version = desktop_version().to_string();

    let mut updated = content.to_string();
    let mut changed = false;

    for (key, desired, repo) in [
        (
            AXBI_IMAGE_ENV,
            desired_axbi.as_str(),
            MANAGED_AXBI_IMAGE_REPO,
        ),
        (
            AX_SERVICES_IMAGE_ENV,
            desired_services.as_str(),
            MANAGED_AX_SERVICES_IMAGE_REPO,
        ),
    ] {
        let current = read_env_value_from_str(&updated, key).unwrap_or_default();
        if current == desired {
            continue;
        }
        if !is_managed_image_ref(&current, repo) {
            continue;
        }
        updated = upsert_env_key_content(&updated, key, desired);
        changed = true;
    }

    let current_version =
        read_env_value_from_str(&updated, AXBI_DESKTOP_VERSION_ENV).unwrap_or_default();
    if current_version != desired_version {
        updated = upsert_env_key_content(&updated, AXBI_DESKTOP_VERSION_ENV, &desired_version);
        changed = true;
    }

    changed.then_some(updated)
}

/// Insert or replace a single KEY=value line in env-file content.
fn upsert_env_key_content(content: &str, key: &str, value: &str) -> String {
    let mut lines: Vec<&str> = content
        .lines()
        .filter(|line| {
            !line
                .split_once('=')
                .map(|(line_key, _)| line_key.trim() == key)
                .unwrap_or(false)
        })
        .collect();
    while lines.last().is_some_and(|line| line.trim().is_empty()) {
        lines.pop();
    }

    let mut updated = lines.join("\n");
    if !updated.is_empty() {
        updated.push('\n');
    }
    updated.push_str(&format!("{key}={value}\n"));
    updated
}

fn ensure_colima_profile(env_path: &Path, compose_path: &Path) -> Result<(), String> {
    if !cfg!(target_os = "macos")
        || read_env_value(env_path, COLIMA_PROFILE_ENV)?
            .filter(|profile| valid_colima_profile(profile))
            .is_some()
    {
        return Ok(());
    }

    let runtime_dir = compose_path.parent().unwrap_or_else(|| Path::new("."));
    // Legacy Desktop releases used Colima's default profile. New environments
    // write `ax-bi` into .env immediately, so a missing key is an upgrade case.
    let profile = if colima_profile_has_managed_axbi(AXBI_COLIMA_PROFILE, runtime_dir) {
        AXBI_COLIMA_PROFILE
    } else {
        "default"
    };
    let mut content = fs::read_to_string(env_path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    if !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(&format!("{COLIMA_PROFILE_ENV}={profile}\n"));
    write_runtime_env(env_path, &content)
}

fn configured_colima_profile(env_path: &Path) -> String {
    read_env_value(env_path, COLIMA_PROFILE_ENV)
        .ok()
        .flatten()
        .filter(|profile| valid_colima_profile(profile))
        .unwrap_or_else(|| AXBI_COLIMA_PROFILE.to_string())
}

fn valid_colima_profile(profile: &str) -> bool {
    !profile.is_empty()
        && profile
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '-' | '_'))
}

fn colima_profile_has_managed_axbi(profile: &str, runtime_dir: &Path) -> bool {
    let Ok(host) = docker_host(profile) else {
        return false;
    };
    if !docker_daemon_ready(&host) {
        return false;
    }

    let project_filter = format!("label=com.docker.compose.project={AXBI_COMPOSE_PROJECT}");
    let service_filter = "label=com.docker.compose.service=ax-bi";
    let runtime_filter = format!(
        "label=com.docker.compose.project.working_dir={}",
        path_to_string(runtime_dir)
    );
    run_command(
        "docker",
        &[
            "ps",
            "--all",
            "--filter",
            &project_filter,
            "--filter",
            service_filter,
            "--filter",
            &runtime_filter,
            "--format",
            "{{.ID}}",
        ],
        None,
        &[("DOCKER_HOST", &host)],
    )
    .map(|output| !output.stdout.trim().is_empty())
    .unwrap_or(false)
}

fn random_hex(byte_count: usize) -> Result<String, String> {
    let mut bytes = vec![0; byte_count];
    getrandom::fill(&mut bytes)
        .map_err(|error| format!("Failed to read secure random source: {error}"))?;
    Ok(bytes
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<Vec<_>>()
        .join(""))
}

fn dependencies() -> Vec<LocalRuntimeDependency> {
    LOCAL_RUNTIME_DEPENDENCIES
        .get_or_init(detect_dependencies)
        .clone()
}

/// Detect independent CLI dependencies concurrently and cache them per launch.
fn detect_dependencies() -> Vec<LocalRuntimeDependency> {
    let join_checks = |handles: Vec<thread::ScopedJoinHandle<'_, LocalRuntimeDependency>>| {
        handles
            .into_iter()
            .map(|handle| {
                handle.join().unwrap_or_else(|_| LocalRuntimeDependency {
                    name: "Runtime dependency".to_string(),
                    command: "unknown".to_string(),
                    resolved_path: String::new(),
                    installed: false,
                    version: None,
                    install_hint: "Restart AX BI Desktop and retry dependency detection"
                        .to_string(),
                })
            })
            .collect()
    };

    match RuntimeEngine::current() {
        RuntimeEngine::Colima => thread::scope(|scope| {
            join_checks(vec![
                scope.spawn(|| {
                    dependency("Colima", "colima", &["--version"], "brew install colima")
                }),
                scope.spawn(|| dependency("Lima", "limactl", &["--version"], "brew install lima")),
                scope.spawn(|| {
                    dependency(
                        "Docker CLI",
                        "docker",
                        &["--version"],
                        "brew install docker",
                    )
                }),
                scope.spawn(|| {
                    dependency(
                        "Docker Compose",
                        "docker",
                        &["compose", "version"],
                        "brew install docker-compose",
                    )
                }),
            ])
        }),
        RuntimeEngine::Docker => thread::scope(|scope| {
            join_checks(vec![
                scope.spawn(|| {
                    dependency(
                        "Docker CLI",
                        "docker",
                        &["--version"],
                        docker_install_hint(),
                    )
                }),
                scope.spawn(|| {
                    dependency(
                        "Docker Compose",
                        "docker",
                        &["compose", "version"],
                        docker_install_hint(),
                    )
                }),
            ])
        }),
    }
}

fn docker_install_hint() -> &'static str {
    if cfg!(target_os = "windows") {
        "Install Docker Desktop (winget install -e --id Docker.DockerDesktop) or from https://docs.docker.com/desktop/setup/install/windows-install/ and ensure it is running"
    } else if cfg!(target_os = "macos") {
        "brew install docker docker-compose"
    } else {
        "Install Docker Engine and the Compose plugin for your distribution"
    }
}

fn platform_id() -> &'static str {
    if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "windows") {
        "windows"
    } else {
        "linux"
    }
}

fn platform_label() -> &'static str {
    if cfg!(target_os = "macos") {
        "macOS"
    } else if cfg!(target_os = "windows") {
        "Windows"
    } else {
        "Linux"
    }
}

/// Fail fast with install hints when CLI tools are missing (before starting engines).
fn ensure_cli_dependencies() -> Result<(), String> {
    let missing: Vec<LocalRuntimeDependency> = dependencies()
        .into_iter()
        .filter(|dependency| !dependency.installed)
        .collect();
    if missing.is_empty() {
        return Ok(());
    }

    let details = missing
        .iter()
        .map(|dependency| format!("- {}: {}", dependency.name, dependency.install_hint))
        .collect::<Vec<_>>()
        .join("\n");

    Err(format!(
        "Cannot start local AX BI Docker on {} — missing tools:\n{}\n\n\
         Run locally uses the same AX BI Compose stack on macOS and Windows \
         (Colima on Mac, Docker Desktop on Windows).",
        platform_label(),
        details
    ))
}

fn format_compose_error(action: &str, error: &str, runtime_dir: Option<&Path>) -> String {
    let diagnostics = runtime_dir
        .map(compose_failure_diagnostics)
        .unwrap_or_default();
    format!(
        "Failed to {action} the local AX BI Docker stack on {}.\n\
         Engine: {} ({})\n\
         {}{}\n\n\
         Tips:\n\
         - Open Settings > Advanced runtime to inspect service logs\n\
         - Stop other applications using the configured AX BI ports, then retry\n\
         - macOS: confirm Colima is running; Windows: confirm Docker Desktop is running",
        platform_label(),
        RuntimeEngine::current().label(),
        RuntimeEngine::current().name(),
        bounded_output_tail(error, 80, 12_000),
        diagnostics,
    )
}

/// Collect bounded service state and logs after a Compose command fails.
fn compose_failure_diagnostics(runtime_dir: &Path) -> String {
    let mut diagnostics = String::new();
    if let Ok(output) = run_docker_compose(runtime_dir, &["ps", "--all"]) {
        diagnostics.push_str(&format_output(
            "compose service state",
            &bounded_output_tail(&join_outputs(&output.stdout, &output.stderr), 80, 8_000),
        ));
    }
    if let Ok(output) = run_docker_compose(
        runtime_dir,
        &[
            "logs",
            "--no-color",
            "--tail",
            "80",
            "ax-bi-init",
            "ax-bi",
            "mcp",
            "ax-services",
        ],
    ) {
        diagnostics.push_str(&format_output(
            "recent startup logs",
            &bounded_output_tail(&join_outputs(&output.stdout, &output.stderr), 160, 16_000),
        ));
    }
    diagnostics
}

/// Keep the actionable tail of noisy subprocess output within UI-safe bounds.
fn bounded_output_tail(value: &str, max_lines: usize, max_chars: usize) -> String {
    let normalized = value.replace('\r', "\n");
    let lines: Vec<&str> = normalized.lines().collect();
    let start = lines.len().saturating_sub(max_lines);
    let mut tail = lines[start..].join("\n");
    let char_count = tail.chars().count();
    if char_count > max_chars {
        tail = tail
            .chars()
            .skip(char_count - max_chars)
            .collect::<String>();
    }
    tail.trim().to_string()
}

fn dependency(
    name: &str,
    command: &str,
    args: &[&str],
    install_hint: &str,
) -> LocalRuntimeDependency {
    match run_command(command, args, None, &[]) {
        Ok(output) => LocalRuntimeDependency {
            name: name.to_string(),
            command: if args.is_empty() {
                command.to_string()
            } else {
                format!("{command} {}", args.join(" "))
            },
            resolved_path: path_to_string(&resolve_program(command)),
            installed: true,
            version: first_line(&join_outputs(&output.stdout, &output.stderr)),
            install_hint: install_hint.to_string(),
        },
        Err(_) => LocalRuntimeDependency {
            name: name.to_string(),
            command: command.to_string(),
            resolved_path: path_to_string(&resolve_program(command)),
            installed: false,
            version: None,
            install_hint: install_hint.to_string(),
        },
    }
}

fn first_line(value: &str) -> Option<String> {
    value.lines().next().map(str::trim).and_then(|line| {
        if line.is_empty() {
            None
        } else {
            Some(line.to_string())
        }
    })
}

/// Ensure the platform container engine is running.
fn ensure_engine(runtime_dir: &Path) -> Result<CommandOutput, String> {
    match RuntimeEngine::current() {
        RuntimeEngine::Colima => {
            run_colima_start(&configured_colima_profile(&env_file(runtime_dir)))
        }
        RuntimeEngine::Docker => ensure_docker_engine(runtime_dir),
    }
}

fn run_colima_start(profile: &str) -> Result<CommandOutput, String> {
    // Explicit limactl check gives a clearer error than Colima's PATH fatality.
    let limactl = resolve_program("limactl");
    if !limactl.is_file() {
        return Err("Lima (limactl) was not found. Colima requires Lima.\n\
             Install with: brew install lima colima\n\
             If already installed, ensure /opt/homebrew/bin is available."
            .to_string());
    }

    let mut prior_output = CommandOutput {
        stdout: String::new(),
        stderr: String::new(),
    };
    let docker_host = docker_host(profile)?;
    if docker_daemon_ready(&docker_host) {
        // Colima's CLI status path can take several seconds. Its generated
        // profile is enough to validate resources once Docker is responsive.
        if colima_resources_sufficient(profile).unwrap_or(true) {
            return Ok(CommandOutput {
                stdout: format!(
                    "Colima profile {profile} is already running with sufficient resources"
                ),
                stderr: String::new(),
            });
        }
        prior_output = run_command("colima", &["stop", "--profile", profile], None, &[])?;
    }

    let start_output = run_command(
        "colima",
        &[
            "start",
            "--profile",
            profile,
            "--runtime",
            "docker",
            "--cpu",
            AXBI_COLIMA_CPUS,
            "--memory",
            AXBI_COLIMA_MEMORY_GB,
            "--activate=false",
        ],
        None,
        &[],
    )?;
    Ok(CommandOutput {
        stdout: join_outputs(&prior_output.stdout, &start_output.stdout),
        stderr: join_outputs(&prior_output.stderr, &start_output.stderr),
    })
}

fn colima_resources_sufficient(profile: &str) -> Option<bool> {
    if !valid_colima_profile(profile) {
        return None;
    }
    let config = fs::read_to_string(
        home_dir()
            .ok()?
            .join(".colima")
            .join(profile)
            .join("colima.yaml"),
    )
    .ok()?;
    colima_config_resources_sufficient(&config)
}

/// Parse top-level Colima CPU and memory settings without invoking its slow CLI.
fn colima_config_resources_sufficient(config: &str) -> Option<bool> {
    let mut cpu = None;
    let mut memory = None;
    for line in config.lines() {
        if line.chars().next().is_some_and(char::is_whitespace) {
            continue;
        }
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        match key.trim() {
            "cpu" => cpu = value.trim().parse::<u64>().ok(),
            "memory" => memory = value.trim().parse::<u64>().ok(),
            _ => {}
        }
    }
    let required_cpu = AXBI_COLIMA_CPUS.parse::<u64>().unwrap_or(4);
    let required_memory = AXBI_COLIMA_MEMORY_GB.parse::<u64>().unwrap_or(8);
    Some(cpu? >= required_cpu && memory? >= required_memory)
}

fn ensure_docker_engine(runtime_dir: &Path) -> Result<CommandOutput, String> {
    let docker_host = docker_host(&configured_colima_profile(&env_file(runtime_dir)))?;
    if docker_daemon_ready(&docker_host) {
        return Ok(CommandOutput {
            stdout: format!(
                "Docker engine already running on {} ({docker_host})",
                platform_label()
            ),
            stderr: String::new(),
        });
    }

    // Launch Docker Desktop when the CLI exists but the daemon is down.
    if let Some(desktop) = docker_desktop_app_path() {
        log::info!("Starting Docker Desktop at {}", desktop.display());
        let mut command = Command::new(&desktop);
        configure_subprocess(&mut command);
        command.spawn().map_err(|error| {
            format!(
                "Docker Engine is not running and Docker Desktop failed to start: {error}\n{}",
                docker_install_hint()
            )
        })?;

        if wait_for_docker_daemon(&docker_host, DOCKER_ENGINE_WAIT)? {
            return Ok(CommandOutput {
                stdout: format!(
                    "Started Docker Desktop on {} and waited for the engine",
                    platform_label()
                ),
                stderr: String::new(),
            });
        }

        return Err(format!(
            "Docker Desktop was launched on {} but the engine did not become ready in time.\n\
             Open Docker Desktop, wait until it reports Running, then try Run locally again.\n\
             Expected Docker host: {docker_host}",
            platform_label()
        ));
    }

    Err(format!(
        "Docker Engine is not available on {}.\n{}",
        platform_label(),
        docker_install_hint()
    ))
}

fn wait_for_docker_daemon(docker_host: &str, timeout: Duration) -> Result<bool, String> {
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        if docker_daemon_ready(docker_host) {
            return Ok(true);
        }
        thread::sleep(DOCKER_ENGINE_POLL);
    }
    Ok(false)
}

fn docker_daemon_ready(docker_host: &str) -> bool {
    let envs = docker_host_envs(docker_host);
    let env_refs: Vec<(&str, &str)> = envs.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    run_command("docker", &["info"], None, &env_refs).is_ok()
}

fn run_docker_compose(runtime_dir: &Path, compose_args: &[&str]) -> Result<CommandOutput, String> {
    run_docker_compose_owned(
        runtime_dir,
        compose_args.iter().map(ToString::to_string).collect(),
    )
}

fn run_docker_compose_owned(
    runtime_dir: &Path,
    compose_args: Vec<String>,
) -> Result<CommandOutput, String> {
    let compose_path = compose_file(runtime_dir);
    let env_path = env_file(runtime_dir);
    let mut args = vec![
        "compose".to_string(),
        "--project-name".to_string(),
        AXBI_COMPOSE_PROJECT.to_string(),
        "--env-file".to_string(),
        path_to_string(&env_path),
        "-f".to_string(),
        path_to_string(&compose_path),
    ];
    args.extend(compose_args);
    let docker_host = docker_host(&configured_colima_profile(&env_file(runtime_dir)))?;
    let envs = docker_host_envs(&docker_host);
    let env_refs: Vec<(&str, &str)> = envs.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    run_command("docker", &arg_refs, Some(runtime_dir), &env_refs)
}

/// Start Compose and reconcile transient command failures against final health.
fn start_compose_stack(runtime_dir: &Path) -> Result<CommandOutput, String> {
    match run_docker_compose(runtime_dir, &["up", "-d", "--remove-orphans"]) {
        Ok(output) => {
            wait_for_runtime_health(runtime_dir)
                .map_err(|error| format_compose_error("start", &error, Some(runtime_dir)))?;
            Ok(output)
        }
        Err(error) => {
            if wait_for_runtime_health_for(runtime_dir, COMPOSE_FAILURE_RECONCILE_WAIT).is_ok() {
                return Ok(CommandOutput {
                    stdout:
                        "Compose reported a transient startup failure, but AX BI became healthy"
                            .to_string(),
                    stderr: bounded_output_tail(&error, 40, 6_000),
                });
            }
            Err(format_compose_error("start", &error, Some(runtime_dir)))
        }
    }
}

fn compose_services_running(runtime_dir: &Path) -> Result<bool, String> {
    Ok(compose_running_services(runtime_dir)?.contains("ax-bi"))
}

/// Return the set of running services owned by the managed Compose project.
fn compose_running_services(runtime_dir: &Path) -> Result<HashSet<String>, String> {
    if !compose_file(runtime_dir).exists() || !env_file(runtime_dir).exists() {
        return Ok(HashSet::new());
    }
    let output = run_docker_compose_owned(
        runtime_dir,
        vec![
            "ps".to_string(),
            "--status".to_string(),
            "running".to_string(),
            "--services".to_string(),
        ],
    )?;

    Ok(output
        .stdout
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(ToString::to_string)
        .collect())
}

fn wait_for_runtime_health(runtime_dir: &Path) -> Result<(), String> {
    wait_for_runtime_health_for(runtime_dir, STARTUP_HEALTH_RECONCILE_WAIT)
}

/// Wait up to the supplied timeout for the managed web service to become healthy.
fn wait_for_runtime_health_for(runtime_dir: &Path, timeout: Duration) -> Result<(), String> {
    let deadline = Instant::now() + timeout;
    let mut last_ps = String::new();
    let urls = runtime_urls(&env_file(runtime_dir));

    while Instant::now() < deadline {
        if compose_services_running(runtime_dir).unwrap_or(false)
            && local_http_healthcheck(urls.web_port)
        {
            return Ok(());
        }

        if let Ok(output) = run_docker_compose(runtime_dir, &["ps"]) {
            last_ps = join_outputs(&output.stdout, &output.stderr);
        }
        thread::sleep(STARTUP_HEALTH_RECONCILE_POLL);
    }

    Err(format!(
        "AX BI containers started, but the web app did not become healthy within {} seconds.{}",
        timeout.as_secs(),
        format_output("compose ps", &last_ps)
    ))
}

fn local_runtime_ports(
    urls: &RuntimeUrls,
    running_services: &HashSet<String>,
) -> Vec<LocalRuntimePort> {
    vec![
        local_runtime_port(
            "AX BI web",
            "ax-bi",
            urls.web_port,
            &urls.web_url,
            running_services,
        ),
        local_runtime_port("MCP", "mcp", urls.mcp_port, &urls.mcp_url, running_services),
        local_runtime_port(
            "AX services",
            "ax-services",
            urls.services_port,
            &urls.services_url,
            running_services,
        ),
    ]
}

fn local_runtime_port(
    name: &str,
    service: &str,
    port: u16,
    url: &str,
    running_services: &HashSet<String>,
) -> LocalRuntimePort {
    let open = tcp_port_open(port);
    local_runtime_port_from_state(name, port, url, open, running_services.contains(service))
}

/// Derive port availability from listener and managed-service state.
fn local_runtime_port_from_state(
    name: &str,
    port: u16,
    url: &str,
    open: bool,
    managed_service_running: bool,
) -> LocalRuntimePort {
    let occupied_by_axbi = open && managed_service_running;
    LocalRuntimePort {
        name: name.to_string(),
        port,
        url: url.to_string(),
        available: !open || occupied_by_axbi,
        occupied_by_axbi,
    }
}

fn ensure_required_ports_available(runtime_dir: &Path) -> Result<(), String> {
    let urls = runtime_urls(&env_file(runtime_dir));
    let running_services = compose_running_services(runtime_dir).unwrap_or_default();
    let blocked: Vec<LocalRuntimePort> = local_runtime_ports(&urls, &running_services)
        .into_iter()
        .filter(|port| !port.available)
        .collect();
    if blocked.is_empty() {
        return Ok(());
    }

    let details = blocked
        .iter()
        .map(|port| {
            let owner = describe_port_owner(runtime_dir, port.port)
                .map(|owner| format!(" — {owner}"))
                .unwrap_or_default();
            format!("- {} port {} ({}){owner}", port.name, port.port, port.url)
        })
        .collect::<Vec<_>>()
        .join("\n");
    Err(format!(
        "Cannot start local AX BI because required port(s) are already in use:\n{}\n\n\
         Stop the other service or change the AX BI ports in the local runtime settings.",
        details
    ))
}

/// Identify a Docker container or host process listening on a blocked port.
fn describe_port_owner(runtime_dir: &Path, port: u16) -> Option<String> {
    if let Ok(host) = docker_host(&configured_colima_profile(&env_file(runtime_dir))) {
        let envs = docker_host_envs(&host);
        let env_refs: Vec<(&str, &str)> = envs
            .iter()
            .map(|(key, value)| (key.as_str(), value.as_str()))
            .collect();
        let port_filter = format!("publish={port}");
        if let Ok(output) = run_command(
            "docker",
            &[
                "ps",
                "--filter",
                &port_filter,
                "--format",
                "{{.Names}} (Docker container {{.ID}})",
            ],
            None,
            &env_refs,
        ) {
            if let Some(owner) = first_line(&output.stdout) {
                return Some(owner);
            }
        }
    }
    host_port_owner(port)
}

/// Identify the first host process listening on a TCP port.
#[cfg(unix)]
fn host_port_owner(port: u16) -> Option<String> {
    let port_selector = format!("-iTCP:{port}");
    let output = run_command(
        "lsof",
        &["-nP", &port_selector, "-sTCP:LISTEN", "-Fpc"],
        None,
        &[],
    )
    .ok()?;
    parse_lsof_port_owner(&output.stdout)
}

/// Parse `lsof -Fpc` output into a concise process description.
#[cfg(unix)]
fn parse_lsof_port_owner(output: &str) -> Option<String> {
    let pid = output.lines().find_map(|line| line.strip_prefix('p'))?;
    let command = output
        .lines()
        .find_map(|line| line.strip_prefix('c'))
        .unwrap_or("process");
    Some(format!("{command} (PID {pid})"))
}

/// Identify the first Windows process listening on a TCP port.
#[cfg(windows)]
fn host_port_owner(port: u16) -> Option<String> {
    let output = run_command("netstat", &["-ano", "-p", "TCP"], None, &[]).ok()?;
    let port_suffix = format!(":{port}");
    output.stdout.lines().find_map(|line| {
        let fields: Vec<&str> = line.split_whitespace().collect();
        (fields.len() >= 5
            && fields[1].ends_with(&port_suffix)
            && fields[3].eq_ignore_ascii_case("LISTENING"))
        .then(|| format!("Windows process PID {}", fields[4]))
    })
}

fn tcp_port_open(port: u16) -> bool {
    tcp_socket_addr(port)
        .and_then(|addr| TcpStream::connect_timeout(&addr, Duration::from_millis(250)).ok())
        .is_some()
}

fn tcp_socket_addr(port: u16) -> Option<SocketAddr> {
    (AXBI_HEALTH_HOST, port)
        .to_socket_addrs()
        .ok()
        .and_then(|mut addresses| addresses.next())
}

fn runtime_urls(env_path: &Path) -> RuntimeUrls {
    let web_port = read_env_port(env_path, "AXBI_PORT", AXBI_HEALTH_PORT);
    let mcp_port = read_env_port(env_path, "MCP_PORT", AXBI_MCP_PORT);
    let services_port = read_env_port(env_path, "AX_SERVICES_PORT", AXBI_SERVICES_PORT);

    RuntimeUrls {
        web_port,
        mcp_port,
        services_port,
        web_url: format!("http://127.0.0.1:{web_port}/ax-bi/welcome/"),
        mcp_url: format!("http://127.0.0.1:{mcp_port}/mcp"),
        services_url: format!("http://127.0.0.1:{services_port}"),
    }
}

fn read_env_port(env_path: &Path, key: &str, default: u16) -> u16 {
    read_env_value(env_path, key)
        .ok()
        .flatten()
        .and_then(|value| value.parse::<u16>().ok())
        .unwrap_or(default)
}

fn run_command(
    program: &str,
    args: &[&str],
    cwd: Option<&Path>,
    envs: &[(&str, &str)],
) -> Result<CommandOutput, String> {
    run_command_with_timeout(program, args, cwd, envs, COMMAND_TIMEOUT)
}

fn run_command_with_timeout(
    program: &str,
    args: &[&str],
    cwd: Option<&Path>,
    envs: &[(&str, &str)],
    timeout: Duration,
) -> Result<CommandOutput, String> {
    let program_path = resolve_program(program);
    let mut command = Command::new(&program_path);
    command.args(args.iter().map(OsStr::new));
    if let Some(cwd) = cwd {
        command.current_dir(cwd);
    }
    command.stdin(Stdio::null());
    command.stdout(Stdio::piped());
    command.stderr(Stdio::piped());
    configure_subprocess(&mut command);
    apply_env_pairs(&mut command, envs);

    let child = command.spawn().map_err(|error| {
        format!(
            "Failed to run {program} (resolved as {}): {error}",
            program_path.display()
        )
    })?;
    let pid = child.id();

    let (tx, rx) = mpsc::channel();
    thread::spawn(move || {
        let result = child.wait_with_output();
        let _ = tx.send(result);
    });

    let output = match rx.recv_timeout(timeout) {
        Ok(Ok(output)) => output,
        Ok(Err(error)) => {
            return Err(format!(
                "Failed to run {program} (resolved as {}): {error}",
                program_path.display()
            ));
        }
        Err(mpsc::RecvTimeoutError::Timeout) => {
            kill_process_tree(pid);
            // Drain the waiter so the OS reaps the process.
            let _ = rx.recv_timeout(Duration::from_secs(2));
            return Err(format!(
                "{program} timed out after {}s and was terminated",
                timeout.as_secs()
            ));
        }
        Err(mpsc::RecvTimeoutError::Disconnected) => {
            kill_process_tree(pid);
            return Err(format!(
                "Failed to run {program}: subprocess waiter disconnected"
            ));
        }
    };

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    if !output.status.success() {
        return Err(format!(
            "{program} exited with status {}{}{}",
            output.status,
            format_output("stdout", &stdout),
            format_output("stderr", &stderr)
        ));
    }

    Ok(CommandOutput { stdout, stderr })
}

/// Best-effort kill of a hung subprocess (and children on Windows).
fn kill_process_tree(pid: u32) {
    if pid == 0 {
        return;
    }

    #[cfg(unix)]
    {
        let _ = Command::new("kill")
            .args(["-TERM", &pid.to_string()])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
        thread::sleep(Duration::from_millis(200));
        let _ = Command::new("kill")
            .args(["-KILL", &pid.to_string()])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }

    #[cfg(windows)]
    {
        let _ = Command::new("taskkill")
            .args(["/PID", &pid.to_string(), "/T", "/F"])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

/// Shared subprocess setup for GUI apps: fixed PATH + no console flash on Windows.
fn configure_subprocess(command: &mut Command) {
    apply_augmented_path(command);
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        // CREATE_NO_WINDOW — avoid flashing consoles when spawning docker/colima.
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }
}

fn apply_env_pairs(command: &mut Command, envs: &[(&str, &str)]) {
    for (key, value) in envs {
        if *key == "DOCKER_HOST" && value.is_empty() {
            command.env_remove("DOCKER_HOST");
        } else {
            command.env(key, value);
        }
    }
}

/// Resolve Homebrew / Docker Desktop binaries for GUI-launched applications.
///
/// Finder, Dock, and Windows shortcuts do not inherit the user's interactive
/// shell PATH, so known install prefixes are checked before PATH lookup.
fn resolve_program(program: &str) -> PathBuf {
    for dir in known_bin_dirs() {
        let candidate = dir.join(program_filename(program));
        if candidate.is_file() {
            return candidate;
        }
    }

    if let Some(from_path) = which_on_augmented_path(program) {
        return from_path;
    }

    PathBuf::from(program_filename(program))
}

fn program_filename(program: &str) -> String {
    if cfg!(target_os = "windows") && !program.ends_with(".exe") {
        format!("{program}.exe")
    } else {
        program.to_string()
    }
}

fn which_on_augmented_path(program: &str) -> Option<PathBuf> {
    let name = program_filename(program);
    let path_var = augmented_path();
    for dir in std::env::split_paths(&path_var) {
        let candidate = dir.join(&name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

fn known_bin_dirs() -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    #[cfg(target_os = "macos")]
    {
        dirs.push(PathBuf::from("/opt/homebrew/bin"));
        dirs.push(PathBuf::from("/opt/homebrew/sbin"));
        dirs.push(PathBuf::from("/usr/local/bin"));
        dirs.push(PathBuf::from("/usr/local/sbin"));
        dirs.push(PathBuf::from("/usr/sbin"));
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(program_files) = std::env::var("ProgramFiles") {
            dirs.push(
                PathBuf::from(&program_files)
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
            // Newer Docker Desktop installs also expose CLI next to the app.
            dirs.push(PathBuf::from(&program_files).join("Docker").join("Docker"));
            dirs.push(
                PathBuf::from(&program_files)
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("cli-plugins"),
            );
        }
        if let Ok(program_files_x86) = std::env::var("ProgramFiles(x86)") {
            dirs.push(
                PathBuf::from(program_files_x86)
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
        }
        if let Ok(local_app_data) = std::env::var("LOCALAPPDATA") {
            dirs.push(
                PathBuf::from(&local_app_data)
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
            dirs.push(
                PathBuf::from(local_app_data)
                    .join("Programs")
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
        }
        // User PATH often includes this after Docker Desktop install.
        if let Ok(user_profile) = std::env::var("USERPROFILE") {
            dirs.push(
                PathBuf::from(user_profile)
                    .join("AppData")
                    .join("Local")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
        }
    }

    #[cfg(target_os = "linux")]
    {
        dirs.push(PathBuf::from("/usr/local/bin"));
        dirs.push(PathBuf::from("/usr/bin"));
        dirs.push(PathBuf::from("/usr/sbin"));
        if let Ok(home) = std::env::var("HOME") {
            dirs.push(PathBuf::from(home).join(".local").join("bin"));
        }
    }

    dirs
}

/// PATH that includes known install prefixes so child tools (e.g. Colima → limactl)
/// resolve correctly when the desktop app is launched without a login shell.
fn augmented_path() -> String {
    let mut parts: Vec<PathBuf> = known_bin_dirs();
    if let Some(existing) = std::env::var_os("PATH") {
        parts.extend(std::env::split_paths(&existing));
    }
    // Deduplicate while preserving order.
    let mut seen = std::collections::HashSet::new();
    parts.retain(|p| seen.insert(p.clone()));
    std::env::join_paths(parts)
        .map(|os| os.to_string_lossy().into_owned())
        .unwrap_or_else(|_| std::env::var("PATH").unwrap_or_default())
}

fn apply_augmented_path(command: &mut Command) {
    command.env("PATH", augmented_path());
}

fn format_output(label: &str, value: &str) -> String {
    if value.trim().is_empty() {
        String::new()
    } else {
        format!("\n{label}:\n{}", value.trim())
    }
}

fn docker_host(colima_profile: &str) -> Result<String, String> {
    match RuntimeEngine::current() {
        RuntimeEngine::Colima => {
            let home = home_dir()?;
            Ok(format!(
                "unix://{}/.colima/{colima_profile}/docker.sock",
                path_to_string(&home)
            ))
        }
        // Pin the local engine endpoint so a stale inherited DOCKER_HOST cannot break us.
        RuntimeEngine::Docker => {
            if cfg!(target_os = "windows") {
                Ok("npipe:////./pipe/docker_engine".to_string())
            } else {
                Ok("unix:///var/run/docker.sock".to_string())
            }
        }
    }
}

fn docker_host_envs(docker_host: &str) -> Vec<(String, String)> {
    // Always set DOCKER_HOST for managed runtime commands (including platform default).
    vec![("DOCKER_HOST".to_string(), docker_host.to_string())]
}

fn home_dir() -> Result<PathBuf, String> {
    if let Ok(home) = std::env::var("HOME") {
        return Ok(PathBuf::from(home));
    }
    #[cfg(target_os = "windows")]
    if let Ok(profile) = std::env::var("USERPROFILE") {
        return Ok(PathBuf::from(profile));
    }
    Err("Home directory is not set (HOME / USERPROFILE)".to_string())
}

/// Path to Docker Desktop app when installed (Windows; optional macOS fallback).
fn docker_desktop_app_path() -> Option<PathBuf> {
    let mut candidates = Vec::new();

    #[cfg(target_os = "windows")]
    {
        if let Ok(program_files) = std::env::var("ProgramFiles") {
            candidates.push(
                PathBuf::from(program_files)
                    .join("Docker")
                    .join("Docker")
                    .join("Docker Desktop.exe"),
            );
        }
        if let Ok(program_files_x86) = std::env::var("ProgramFiles(x86)") {
            candidates.push(
                PathBuf::from(program_files_x86)
                    .join("Docker")
                    .join("Docker")
                    .join("Docker Desktop.exe"),
            );
        }
        if let Ok(local_app_data) = std::env::var("LOCALAPPDATA") {
            candidates.push(
                PathBuf::from(local_app_data)
                    .join("Docker")
                    .join("Docker Desktop.exe"),
            );
        }
    }

    #[cfg(target_os = "macos")]
    {
        candidates.push(PathBuf::from(
            "/Applications/Docker.app/Contents/MacOS/Docker",
        ));
    }

    candidates.into_iter().find(|path| path.is_file())
}

fn local_http_healthcheck(port: u16) -> bool {
    let Ok(mut addresses) = (AXBI_HEALTH_HOST, port).to_socket_addrs() else {
        return false;
    };
    let Some(address) = addresses.next() else {
        return false;
    };
    let Ok(mut stream) = TcpStream::connect_timeout(&address, Duration::from_millis(750)) else {
        return false;
    };
    let _ = stream.set_read_timeout(Some(Duration::from_millis(750)));
    let _ = stream.set_write_timeout(Some(Duration::from_millis(750)));

    if stream
        .write_all(b"GET /health HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n")
        .is_err()
    {
        return false;
    }

    let mut response = String::new();
    stream.read_to_string(&mut response).is_ok()
        && (response.starts_with("HTTP/1.1 200") || response.starts_with("HTTP/1.0 200"))
}

fn validate_log_service(service: &str) -> Result<&str, String> {
    let service = service.trim();
    if ALLOWED_LOG_SERVICES.contains(&service) {
        Ok(service)
    } else {
        Err("Unknown local AX BI service name".to_string())
    }
}

fn tail_lines(value: Option<u16>) -> u16 {
    value.unwrap_or(200).clamp(1, MAX_LOG_TAIL_LINES)
}

fn read_env_value(path: &Path, key: &str) -> Result<Option<String>, String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    Ok(read_env_value_from_str(&content, key))
}

fn read_env_value_from_str(content: &str, key: &str) -> Option<String> {
    content.lines().find_map(|line| {
        let trimmed_line = line.trim();
        if trimmed_line.is_empty() || trimmed_line.starts_with('#') {
            return None;
        }
        let (line_key, line_value) = trimmed_line.split_once('=')?;
        if line_key.trim() == key {
            Some(strip_env_value_quotes(line_value.trim()).to_string())
        } else {
            None
        }
    })
}

/// Strip a single pair of matching surrounding quotes from an env value.
fn strip_env_value_quotes(value: &str) -> &str {
    let bytes = value.as_bytes();
    if bytes.len() >= 2 {
        let first = bytes[0];
        let last = bytes[bytes.len() - 1];
        if (first == b'"' && last == b'"') || (first == b'\'' && last == b'\'') {
            return &value[1..value.len() - 1];
        }
    }
    value
}

fn join_outputs(first: &str, second: &str) -> String {
    match (first.trim(), second.trim()) {
        ("", "") => String::new(),
        (first, "") => first.to_string(),
        ("", second) => second.to_string(),
        (first, second) => format!("{first}\n{second}"),
    }
}

fn path_to_string(path: &Path) -> String {
    path.to_string_lossy().to_string()
}

#[cfg(test)]
mod tests {
    #[cfg(unix)]
    use super::parse_lsof_port_owner;
    #[cfg(unix)]
    use super::secure_runtime_env_permissions;
    use super::{
        atomic_write, augmented_path, bounded_output_tail, build_env_file,
        colima_config_resources_sufficient, configured_colima_profile, default_ax_services_image,
        default_axbi_image, desktop_version, docker_host, ensure_managed_image_tags_content,
        ensure_runtime_secrets_content, is_managed_image_ref, local_runtime_port_from_state,
        managed_image_tag, platform_id, platform_label, program_filename, read_env_value_from_str,
        resolve_program, run_command_with_timeout, runtime_urls, strip_env_value_quotes, tail_lines,
        valid_colima_profile, validate_log_service, write_file_if_changed, RuntimeEngine,
        AXBI_ADMIN_USERNAME, AXBI_COLIMA_CPUS, AXBI_COLIMA_MEMORY_GB, AXBI_COLIMA_PROFILE,
        AXBI_DESKTOP_VERSION_ENV, AXBI_IMAGE_ENV, AX_SERVICES_IMAGE_ENV, LOCAL_COMPOSE_YAML,
        MANAGED_AXBI_IMAGE_REPO, MANAGED_AX_SERVICES_IMAGE_REPO, MAX_LOG_TAIL_LINES,
    };
    use std::fs;
    use std::path::Path;
    use std::time::Duration;

    #[test]
    fn generated_compose_binds_public_services_to_loopback() {
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${AXBI_PORT:-31423}:31423"));
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${MCP_PORT:-31421}:31421"));
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${AX_SERVICES_PORT:-31424}:31424"));
        assert!(LOCAL_COMPOSE_YAML.contains("TALISMAN_ENABLED: ${TALISMAN_ENABLED:-false}"));
        assert!(
            LOCAL_COMPOSE_YAML.contains("SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-false}")
        );
        assert!(LOCAL_COMPOSE_YAML.contains("AXBI_PORT: 31423"));
        assert_eq!(
            LOCAL_COMPOSE_YAML
                .matches(
                    "AX_SERVICES_INTERNAL_TOKEN: ${AX_SERVICES_INTERNAL_TOKEN:?Set AX_SERVICES_INTERNAL_TOKEN in .env}"
                )
                .count(),
            2
        );
    }

    #[test]
    fn generated_env_contains_required_secrets() {
        let env_file = build_env_file().unwrap();

        assert!(read_env_value_from_str(&env_file, "AX_BI_SECRET_KEY").is_some());
        assert!(read_env_value_from_str(&env_file, "DATABASE_PASSWORD").is_some());
        let services_token =
            read_env_value_from_str(&env_file, "AX_SERVICES_INTERNAL_TOKEN").unwrap();
        assert_eq!(services_token.len(), 64);
        let admin_password = read_env_value_from_str(&env_file, "ADMIN_PASSWORD").unwrap();
        assert_eq!(admin_password.len(), 36);
        assert_ne!(admin_password, "admin");
        assert_eq!(
            read_env_value_from_str(&env_file, "COLIMA_PROFILE").unwrap(),
            AXBI_COLIMA_PROFILE
        );
        assert_eq!(
            read_env_value_from_str(&env_file, "TALISMAN_ENABLED").unwrap(),
            "false"
        );
        assert_eq!(
            read_env_value_from_str(&env_file, "SESSION_COOKIE_SECURE").unwrap(),
            "false"
        );
        assert_eq!(
            read_env_value_from_str(&env_file, "MCP_DEV_USERNAME").unwrap(),
            AXBI_ADMIN_USERNAME
        );
        assert_eq!(
            read_env_value_from_str(&env_file, AXBI_DESKTOP_VERSION_ENV).unwrap(),
            desktop_version()
        );
        assert_eq!(
            read_env_value_from_str(&env_file, AXBI_IMAGE_ENV).unwrap(),
            default_axbi_image()
        );
        assert_eq!(
            read_env_value_from_str(&env_file, AX_SERVICES_IMAGE_ENV).unwrap(),
            default_ax_services_image()
        );
        assert!(default_axbi_image().ends_with(&format!(":{}", managed_image_tag())));
    }

    #[test]
    fn managed_image_refs_are_re_pinnable_and_custom_overrides_are_preserved() {
        assert!(is_managed_image_ref("", MANAGED_AXBI_IMAGE_REPO));
        assert!(is_managed_image_ref(
            &format!("{MANAGED_AXBI_IMAGE_REPO}:latest"),
            MANAGED_AXBI_IMAGE_REPO
        ));
        assert!(is_managed_image_ref(
            &format!("{MANAGED_AXBI_IMAGE_REPO}:1.2.3"),
            MANAGED_AXBI_IMAGE_REPO
        ));
        assert!(!is_managed_image_ref(
            &format!("{MANAGED_AXBI_IMAGE_REPO}@sha256:abc"),
            MANAGED_AXBI_IMAGE_REPO
        ));
        assert!(!is_managed_image_ref(
            "ghcr.io/other/ax-bi:latest",
            MANAGED_AXBI_IMAGE_REPO
        ));

        let legacy = format!(
            "AXBI_IMAGE={MANAGED_AXBI_IMAGE_REPO}:latest\nAX_SERVICES_IMAGE={MANAGED_AX_SERVICES_IMAGE_REPO}:latest\n"
        );
        let migrated = ensure_managed_image_tags_content(&legacy).expect("should migrate");
        assert_eq!(
            read_env_value_from_str(&migrated, AXBI_IMAGE_ENV).unwrap(),
            default_axbi_image()
        );
        assert_eq!(
            read_env_value_from_str(&migrated, AX_SERVICES_IMAGE_ENV).unwrap(),
            default_ax_services_image()
        );
        assert_eq!(
            read_env_value_from_str(&migrated, AXBI_DESKTOP_VERSION_ENV).unwrap(),
            desktop_version()
        );

        let custom =
            "AXBI_IMAGE=ghcr.io/other/ax-bi:custom\nAX_SERVICES_IMAGE=ghcr.io/other/svc:custom\n";
        let maybe = ensure_managed_image_tags_content(custom);
        // Desktop version key may still be added; images must remain custom.
        if let Some(updated) = maybe {
            assert_eq!(
                read_env_value_from_str(&updated, AXBI_IMAGE_ENV).unwrap(),
                "ghcr.io/other/ax-bi:custom"
            );
            assert_eq!(
                read_env_value_from_str(&updated, AX_SERVICES_IMAGE_ENV).unwrap(),
                "ghcr.io/other/svc:custom"
            );
        }
    }

    #[test]
    fn generated_colima_start_uses_recommended_resources() {
        assert_eq!(AXBI_COLIMA_CPUS, "4");
        assert_eq!(AXBI_COLIMA_MEMORY_GB, "8");
    }

    #[test]
    fn reads_colima_resources_from_profile_without_cli_status() {
        let sufficient = "cpu: 4\nmemory: 8\ndisk: 80\n";
        let insufficient = "cpu: 2\nmemory: 4\ndisk: 80\n";

        assert_eq!(colima_config_resources_sufficient(sufficient), Some(true));
        assert_eq!(
            colima_config_resources_sufficient(insufficient),
            Some(false)
        );
        assert_eq!(colima_config_resources_sufficient("disk: 80\n"), None);
    }

    #[test]
    fn configured_colima_profile_accepts_safe_names_and_rejects_paths() {
        let env_path =
            std::env::temp_dir().join(format!("axbi-profile-test-{}.env", std::process::id()));
        fs::write(&env_path, "COLIMA_PROFILE=default\n").unwrap();
        assert_eq!(configured_colima_profile(&env_path), "default");

        fs::write(&env_path, "COLIMA_PROFILE=../../other\n").unwrap();
        assert_eq!(configured_colima_profile(&env_path), AXBI_COLIMA_PROFILE);
        let _ = fs::remove_file(&env_path);

        assert!(valid_colima_profile("team_ax-bi"));
        assert!(!valid_colima_profile(""));
        assert!(!valid_colima_profile("../ax-bi"));
    }

    #[test]
    fn runtime_urls_default_to_standard_ports_when_env_missing() {
        let urls = runtime_urls(Path::new("/definitely/missing/.env"));

        assert_eq!(urls.web_port, 31423);
        assert_eq!(urls.mcp_port, 31421);
        assert_eq!(urls.services_port, 31424);
        assert_eq!(urls.web_url, "http://127.0.0.1:31423/ax-bi/welcome/");
    }

    #[test]
    fn runtime_urls_follow_env_port_overrides() {
        let env_path =
            std::env::temp_dir().join(format!("axbi-runtime-test-{}.env", std::process::id()));
        fs::write(
            &env_path,
            "AXBI_PORT=18088\nMCP_PORT=15008\nAX_SERVICES_PORT=15010\n",
        )
        .unwrap();

        let urls = runtime_urls(&env_path);
        let _ = fs::remove_file(&env_path);

        assert_eq!(urls.web_port, 18088);
        assert_eq!(urls.mcp_url, "http://127.0.0.1:15008/mcp");
        assert_eq!(urls.services_url, "http://127.0.0.1:15010");
    }

    #[test]
    fn adds_missing_runtime_secrets() {
        let env_file = "COMPOSE_PROJECT_NAME=axbi\nADMIN_PASSWORD=admin\n";
        let updated = ensure_runtime_secrets_content(env_file).unwrap().unwrap();

        assert!(read_env_value_from_str(&updated, "AX_BI_SECRET_KEY").is_some());
        assert!(read_env_value_from_str(&updated, "AX_SERVICES_INTERNAL_TOKEN").is_some());
        assert_eq!(
            read_env_value_from_str(&updated, "ADMIN_PASSWORD").unwrap(),
            "admin"
        );
    }

    #[test]
    fn preserves_existing_runtime_secrets_and_replaces_empty_values() {
        let env_file =
            "AX_BI_SECRET_KEY=existing-secret\nAX_SERVICES_INTERNAL_TOKEN=\nOTHER=value\n";
        let updated = ensure_runtime_secrets_content(env_file).unwrap().unwrap();

        assert_eq!(
            read_env_value_from_str(&updated, "AX_BI_SECRET_KEY").unwrap(),
            "existing-secret"
        );
        assert_eq!(
            read_env_value_from_str(&updated, "AX_SERVICES_INTERNAL_TOKEN")
                .unwrap()
                .len(),
            64
        );
        assert_eq!(read_env_value_from_str(&updated, "OTHER").unwrap(), "value");
        assert!(ensure_runtime_secrets_content(&updated).unwrap().is_none());
    }

    #[cfg(unix)]
    #[test]
    fn secures_runtime_environment_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let env_path =
            std::env::temp_dir().join(format!("axbi-permissions-test-{}.env", std::process::id()));
        fs::write(&env_path, "AX_BI_SECRET_KEY=test\n").unwrap();
        fs::set_permissions(&env_path, fs::Permissions::from_mode(0o644)).unwrap();

        secure_runtime_env_permissions(&env_path).unwrap();
        let mode = fs::metadata(&env_path).unwrap().permissions().mode() & 0o777;
        let _ = fs::remove_file(&env_path);

        assert_eq!(mode, 0o600);
    }

    #[test]
    fn only_managed_compose_services_own_open_runtime_ports() {
        let external = local_runtime_port_from_state(
            "AX BI web",
            31423,
            "http://127.0.0.1:31423",
            true,
            false,
        );
        assert!(!external.available);
        assert!(!external.occupied_by_axbi);

        let managed =
            local_runtime_port_from_state("AX BI web", 31423, "http://127.0.0.1:31423", true, true);
        assert!(managed.available);
        assert!(managed.occupied_by_axbi);
    }

    #[test]
    fn compose_errors_keep_the_actionable_tail_bounded() {
        let noisy = format!("{}\rROOT CAUSE", "pulling layer\r".repeat(200));
        let tail = bounded_output_tail(&noisy, 10, 200);

        assert!(tail.len() <= 200);
        assert!(tail.ends_with("ROOT CAUSE"));
        assert!(tail.lines().count() <= 10);
    }

    #[cfg(unix)]
    #[test]
    fn parses_port_owner_from_lsof_machine_output() {
        assert_eq!(
            parse_lsof_port_owner("p28162\ncpython3.1\np90428\ncpython3.1\n").unwrap(),
            "python3.1 (PID 28162)"
        );
    }

    #[test]
    fn log_services_are_allowlisted() {
        assert_eq!(validate_log_service("ax-bi").unwrap(), "ax-bi");
        assert!(validate_log_service("../../../etc/passwd").is_err());
        assert!(validate_log_service("unknown").is_err());
    }

    #[test]
    fn log_tail_is_clamped() {
        assert_eq!(tail_lines(None), 200);
        assert_eq!(tail_lines(Some(0)), 1);
        assert_eq!(tail_lines(Some(1_000)), MAX_LOG_TAIL_LINES);
    }

    #[test]
    fn leaves_relative_program_names_available_for_path_resolution() {
        assert_eq!(
            resolve_program("command-not-on-path"),
            Path::new(&program_filename("command-not-on-path"))
        );
    }

    #[test]
    fn augmented_path_includes_known_prefixes_on_macos() {
        let path = augmented_path();
        if cfg!(target_os = "macos") {
            assert!(
                path.contains("/opt/homebrew/bin") || path.contains("/usr/local/bin"),
                "expected Homebrew prefix in PATH, got: {path}"
            );
        }
    }

    #[test]
    fn docker_host_matches_platform_engine() {
        let host = docker_host(AXBI_COLIMA_PROFILE).unwrap();
        match RuntimeEngine::current() {
            RuntimeEngine::Colima => {
                assert!(host.contains(AXBI_COLIMA_PROFILE));
                assert!(host.starts_with("unix://"));
            }
            RuntimeEngine::Docker => {
                if cfg!(target_os = "windows") {
                    assert_eq!(host, "npipe:////./pipe/docker_engine");
                } else {
                    assert_eq!(host, "unix:///var/run/docker.sock");
                }
            }
        }
    }

    #[test]
    fn engine_is_colima_only_on_macos() {
        if cfg!(target_os = "macos") {
            assert_eq!(RuntimeEngine::current(), RuntimeEngine::Colima);
            assert_eq!(RuntimeEngine::current().label(), "Colima");
        } else {
            assert_eq!(RuntimeEngine::current(), RuntimeEngine::Docker);
            assert_eq!(RuntimeEngine::current().label(), "Docker Engine");
        }
    }

    #[test]
    fn both_desktop_platforms_support_local_runtime() {
        // Local AX BI Docker is a first-class path on every desktop OS we ship.
        assert!(matches!(
            RuntimeEngine::current(),
            RuntimeEngine::Colima | RuntimeEngine::Docker
        ));
        assert!(!platform_id().is_empty());
        assert!(!platform_label().is_empty());
    }

    #[test]
    fn strips_surrounding_quotes_from_env_values() {
        assert_eq!(strip_env_value_quotes(r#""hello""#), "hello");
        assert_eq!(strip_env_value_quotes("'hello'"), "hello");
        assert_eq!(strip_env_value_quotes("hello"), "hello");
        assert_eq!(strip_env_value_quotes(r#""partial"#), r#""partial"#);
        assert_eq!(
            read_env_value_from_str("ADMIN_PASSWORD=\"s3cret\"\n", "ADMIN_PASSWORD").unwrap(),
            "s3cret"
        );
        assert_eq!(
            read_env_value_from_str("ADMIN_PASSWORD='s3cret'\n", "ADMIN_PASSWORD").unwrap(),
            "s3cret"
        );
    }

    #[test]
    fn atomic_write_and_write_if_changed_are_idempotent() {
        let path = std::env::temp_dir().join(format!(
            "axbi-atomic-write-test-{}.yml",
            std::process::id()
        ));
        let _ = fs::remove_file(&path);

        write_file_if_changed(&path, "one\n", "test file").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "one\n");

        // Unchanged content must not rewrite (still succeeds).
        write_file_if_changed(&path, "one\n", "test file").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "one\n");

        write_file_if_changed(&path, "two\n", "test file").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "two\n");

        atomic_write(&path, "three\n", "test file").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "three\n");

        let _ = fs::remove_file(&path);
    }

    #[test]
    fn run_command_times_out_and_kills_hung_process() {
        let (program, args): (&str, &[&str]) = if cfg!(windows) {
            ("ping", &["127.0.0.1", "-n", "30"])
        } else {
            ("sleep", &["30"])
        };

        let started = std::time::Instant::now();
        let error = run_command_with_timeout(program, args, None, &[], Duration::from_secs(1))
            .expect_err("hung command should time out");
        assert!(
            error.contains("timed out"),
            "unexpected error message: {error}"
        );
        assert!(
            started.elapsed() < Duration::from_secs(10),
            "timeout watchdog took too long: {:?}",
            started.elapsed()
        );
    }
}
