// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! App-managed local AX BI runtime.
//!
//! Platform engines:
//! - **macOS:** isolated Colima profile `ax-bi` (needs Lima / `limactl` on PATH)
//! - **Windows / Linux:** host Docker Engine (typically Docker Desktop)
//!
//! Compose stack and ports are identical across platforms. GUI-launched apps
//! often lack Homebrew/Docker bins on `PATH`; every subprocess gets an
//! augmented PATH so `colima` can find `limactl` and Docker CLIs resolve.

use serde::{Deserialize, Serialize};
use std::ffi::OsStr;
use std::fs;
use std::io::{Read, Write};
use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::thread;
use std::time::{Duration, Instant};
use tauri::{AppHandle, Manager, Runtime};

const AXBI_COLIMA_PROFILE: &str = "ax-bi";
const COLIMA_PROFILE_ENV: &str = "COLIMA_PROFILE";
const AXBI_COMPOSE_PROJECT: &str = "axbi";
const AXBI_ADMIN_USERNAME: &str = "admin";
const AXBI_HEALTH_HOST: &str = "127.0.0.1";
const AXBI_HEALTH_PORT: u16 = 31423;
const AXBI_MCP_PORT: u16 = 31421;
const AXBI_SERVICES_PORT: u16 = 31424;
const AXBI_COLIMA_CPUS: &str = "4";
const AXBI_COLIMA_MEMORY_GB: &str = "8";
const STARTUP_HEALTH_RECONCILE_WAIT: Duration = Duration::from_secs(120);
const STARTUP_HEALTH_RECONCILE_POLL: Duration = Duration::from_secs(2);
const LOCAL_RUNTIME_DIR: &str = "local-runtime";
const LOCAL_ENV_FILE: &str = ".env";
const LOCAL_COMPOSE_FILE: &str = "docker-compose.yml";
const LOCAL_ONBOARDING_COMPLETE_FILE: &str = ".admin-onboarding-complete";
const MAX_LOG_TAIL_LINES: u16 = 500;
const DOCKER_ENGINE_WAIT: Duration = Duration::from_secs(120);
const DOCKER_ENGINE_POLL: Duration = Duration::from_secs(2);

const ALLOWED_LOG_SERVICES: &[&str] = &[
    "redis",
    "db",
    "ax-bi-init",
    "ax-bi",
    "ax-bi-worker",
    "ax-bi-worker-beat",
    "mcp",
    "ax-services",
];

const LOCAL_COMPOSE_YAML: &str = r#"# Generated by AX BI Desktop.
# This file is managed by the desktop local runtime manager.

x-axbi-image: &axbi-image ${AXBI_IMAGE:-ghcr.io/defai-digital/ax-bi:latest}
x-axbi-services-image: &axbi-services-image ${AX_SERVICES_IMAGE:-ghcr.io/defai-digital/ax-bi-services:latest}

x-axbi-env: &axbi-env
  AXBI_CONFIG_PATH: /app/docker/pythonpath_axbi/axbi_config.py
  AXBI_ENV: production
  AXBI_LOAD_EXAMPLES: ${AXBI_LOAD_EXAMPLES:-no}
  AXBI_LOG_LEVEL: ${AXBI_LOG_LEVEL:-info}
  AX_BI_SECRET_KEY: ${AX_BI_SECRET_KEY:?Set AX_BI_SECRET_KEY in .env}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD in .env}
  DATABASE_DIALECT: ${DATABASE_DIALECT:-postgresql}
  DATABASE_HOST: ${DATABASE_HOST:-db}
  DATABASE_PORT: ${DATABASE_PORT:-5432}
  DATABASE_DB: ${DATABASE_DB:-axbi}
  DATABASE_USER: ${DATABASE_USER:-axbi}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:?Set DATABASE_PASSWORD in .env}
  UPLOAD_FOLDER: ${UPLOAD_FOLDER:-/app/axbi_home/uploads}
  LOCAL_DB_NAME: ${LOCAL_DB_NAME:-Local Files}
  LOCAL_DB_PATH: ${LOCAL_DB_PATH:-/app/axbi_home/uploads/local_files.duckdb}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  ENABLE_PROXY_FIX: ${ENABLE_PROXY_FIX:-true}
  TALISMAN_ENABLED: ${TALISMAN_ENABLED:-false}
  MCP_AUTH_ENABLED: ${MCP_AUTH_ENABLED:-false}
  MCP_DEV_USERNAME: ${MCP_DEV_USERNAME:-admin}
  MCP_JWT_ISSUER: ${MCP_JWT_ISSUER:-}
  MCP_JWT_AUDIENCE: ${MCP_JWT_AUDIENCE:-}
  MCP_JWKS_URI: ${MCP_JWKS_URI:-}
  MCP_REQUIRED_SCOPES: ${MCP_REQUIRED_SCOPES:-}
  GENAI_SEMANTIC_INDEX: ${GENAI_SEMANTIC_INDEX:-false}
  GENAI_SEMANTIC_INDEX_PGVECTOR: ${GENAI_SEMANTIC_INDEX_PGVECTOR:-false}
  AI_SEMANTIC_EMBEDDING_PROVIDER: ${AI_SEMANTIC_EMBEDDING_PROVIDER:-ax_engine_http}
  AI_SEMANTIC_EMBEDDING_ENDPOINT: ${AI_SEMANTIC_EMBEDDING_ENDPOINT:-http://host.docker.internal:8099/embed}
  AI_SEMANTIC_EMBEDDING_MODEL: ${AI_SEMANTIC_EMBEDDING_MODEL:-Qwen/Qwen3-Embedding-0.6B}
  AI_SEMANTIC_EMBEDDING_DIMENSIONS: ${AI_SEMANTIC_EMBEDDING_DIMENSIONS:-1024}

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg18}
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB:-axbi}
      POSTGRES_USER: ${POSTGRES_USER:-axbi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?Set DATABASE_PASSWORD in .env}
    volumes:
      - db_home:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-axbi} -d ${POSTGRES_DB:-axbi}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  ax-bi-init:
    image: *axbi-image
    command: ["/app/docker/docker-init.sh"]
    environment: *axbi-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - axbi_home:/app/axbi_home
    healthcheck:
      disable: true

  ax-bi:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:${AXBI_PORT:-31423}:31423"
    environment: *axbi-env
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "/app/docker/docker-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-bi-worker:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: unless-stopped
    environment: *axbi-env
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A axbi.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-bi-worker-beat:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: unless-stopped
    environment: *axbi-env
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    healthcheck:
      disable: true

  mcp:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "mcp"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MCP_PORT:-31421}:31421"
    environment:
      <<: *axbi-env
      MCP_PORT: 31421
    depends_on:
      ax-bi-init:
        condition: service_completed_successfully
    volumes:
      - axbi_home:/app/axbi_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import socket; socket.create_connection(('127.0.0.1', 31421), 5).close()",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-services:
    image: *axbi-services-image
    restart: unless-stopped
    environment:
      AX_SERVICES_HOST: 0.0.0.0
      AX_SERVICES_PORT: 31424
      AXBI_BASE_URL: http://ax-bi:31423
      AX_SERVICES_LOG_LEVEL: ${AX_SERVICES_LOG_LEVEL:-info}
    ports:
      - "127.0.0.1:${AX_SERVICES_PORT:-31424}:31424"
    depends_on:
      ax-bi:
        condition: service_healthy

volumes:
  axbi_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeDependency {
    pub name: String,
    pub command: String,
    pub resolved_path: String,
    pub installed: bool,
    pub version: Option<String>,
    pub install_hint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimePort {
    pub name: String,
    pub port: u16,
    pub url: String,
    pub available: bool,
    pub occupied_by_axbi: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeStatus {
    pub runtime_dir: String,
    pub compose_file: String,
    pub env_file: String,
    pub configured: bool,
    pub dependencies: Vec<LocalRuntimeDependency>,
    pub ports: Vec<LocalRuntimePort>,
    /// OS label: `macos`, `windows`, or `linux`.
    pub platform: String,
    /// Always true on desktop builds — both macOS and Windows can run local AX BI Docker.
    pub local_runtime_supported: bool,
    /// True when required CLI tools are installed (engine may still need to start).
    pub can_start_local: bool,
    /// Engine identifier: `colima` (macOS) or `docker` (Windows/Linux).
    pub engine_name: String,
    /// UI label for the VM/engine layer (e.g. "Colima", "Docker Engine").
    pub engine_label: String,
    /// Whether the container engine is ready enough to run Compose.
    pub engine_running: bool,
    /// Colima profile name on macOS; empty on other platforms.
    pub colima_profile: String,
    /// Backward-compatible alias of engine readiness for Colima-era clients.
    pub colima_running: bool,
    pub docker_host: String,
    pub docker_ready: bool,
    pub axbi_running: bool,
    pub axbi_healthy: bool,
    pub web_url: String,
    pub mcp_url: String,
    pub services_url: String,
    pub admin_username: String,
    pub admin_password_present: bool,
    pub onboarding_required: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeCommandOutput {
    pub status: LocalRuntimeStatus,
    pub stdout: String,
    pub stderr: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalAdminCredentials {
    pub username: String,
    pub password: String,
}

#[derive(Debug)]
struct CommandOutput {
    stdout: String,
    stderr: String,
}

#[derive(Debug, Clone)]
struct RuntimeUrls {
    web_port: u16,
    mcp_port: u16,
    services_port: u16,
    web_url: String,
    mcp_url: String,
    services_url: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RuntimeEngine {
    Colima,
    Docker,
}

impl RuntimeEngine {
    fn current() -> Self {
        if cfg!(target_os = "macos") {
            Self::Colima
        } else {
            Self::Docker
        }
    }

    fn name(self) -> &'static str {
        match self {
            Self::Colima => "colima",
            Self::Docker => "docker",
        }
    }

    fn label(self) -> &'static str {
        match self {
            Self::Colima => "Colima",
            Self::Docker => "Docker Engine",
        }
    }
}

pub fn status<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeStatus, String> {
    log::info!("Checking local AX BI runtime status");
    let runtime_dir = runtime_dir(app)?;
    let compose_file = compose_file(&runtime_dir);
    let env_file = env_file(&runtime_dir);
    log::info!("Reading local runtime dependencies");
    let dependencies = dependencies();
    let urls = runtime_urls(&env_file);
    let ports = local_runtime_ports(&urls);
    let configured = compose_file.exists() && env_file.exists();
    if configured {
        log::info!("Syncing generated local runtime files");
        sync_runtime_files(&compose_file, &env_file)?;
    }

    let engine = RuntimeEngine::current();
    log::info!("Checking {} status", engine.label());
    let colima_profile = configured_colima_profile(&env_file);
    let engine_running = engine_is_running(&colima_profile);
    let docker_host = docker_host(&colima_profile)?;
    log::info!("Checking Docker status");
    let docker_ready = docker_daemon_ready(&docker_host);
    log::info!("Checking Compose service status");
    let axbi_running = docker_ready && compose_services_running(&runtime_dir)?;
    log::info!("Checking AX BI HTTP health");
    let axbi_healthy = axbi_running && local_http_healthcheck(urls.web_port);
    let admin_password_present = configured
        && read_env_value(&env_file, "ADMIN_PASSWORD")
            .ok()
            .flatten()
            .map(|password| !password.is_empty())
            .unwrap_or(false);
    let onboarding_required =
        admin_password_present && !onboarding_complete_file(&runtime_dir).exists();

    let colima_profile = match engine {
        RuntimeEngine::Colima => colima_profile,
        RuntimeEngine::Docker => String::new(),
    };
    let can_start_local = dependencies.iter().all(|dependency| dependency.installed);

    Ok(LocalRuntimeStatus {
        runtime_dir: path_to_string(&runtime_dir),
        compose_file: path_to_string(&compose_file),
        env_file: path_to_string(&env_file),
        configured,
        dependencies,
        ports,
        platform: platform_id().to_string(),
        local_runtime_supported: true,
        can_start_local,
        engine_name: engine.name().to_string(),
        engine_label: engine.label().to_string(),
        engine_running,
        colima_profile,
        // Keep Colima-era field name; UI uses engine_running / engine_label.
        colima_running: engine_running,
        docker_host,
        docker_ready,
        axbi_running,
        axbi_healthy,
        web_url: urls.web_url,
        mcp_url: urls.mcp_url,
        services_url: urls.services_url,
        admin_username: AXBI_ADMIN_USERNAME.to_string(),
        admin_password_present,
        onboarding_required,
    })
}

pub fn prepare<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeStatus, String> {
    ensure_runtime_files(app)?;
    status(app)
}

pub fn start<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    ensure_cli_dependencies()?;
    ensure_required_ports_available(&runtime_dir)?;
    let engine_output = ensure_engine(&runtime_dir)?;
    let compose_output = run_docker_compose(&runtime_dir, &["up", "-d", "--remove-orphans"])
        .map_err(|error| format_compose_error("start", &error))?;
    wait_for_runtime_health(&runtime_dir)?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(&engine_output.stdout, &compose_output.stdout),
        stderr: join_outputs(&engine_output.stderr, &compose_output.stderr),
    })
}

pub fn stop<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    // Stop should still try even if the engine is flaky; surface compose errors clearly.
    let output = run_docker_compose(&runtime_dir, &["stop"])
        .map_err(|error| format_compose_error("stop", &error))?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: output.stdout,
        stderr: output.stderr,
    })
}

pub fn restart<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    ensure_cli_dependencies()?;
    let engine_output = ensure_engine(&runtime_dir)?;
    let stop_output = run_docker_compose(&runtime_dir, &["stop"])
        .map_err(|error| format_compose_error("stop", &error))?;
    ensure_required_ports_available(&runtime_dir)?;
    let start_output = run_docker_compose(&runtime_dir, &["up", "-d", "--remove-orphans"])
        .map_err(|error| format_compose_error("start", &error))?;
    wait_for_runtime_health(&runtime_dir)?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(
            &join_outputs(&engine_output.stdout, &stop_output.stdout),
            &start_output.stdout,
        ),
        stderr: join_outputs(
            &join_outputs(&engine_output.stderr, &stop_output.stderr),
            &start_output.stderr,
        ),
    })
}

pub fn update<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    ensure_cli_dependencies()?;
    let engine_output = ensure_engine(&runtime_dir)?;
    let pull_output = run_docker_compose(&runtime_dir, &["pull"])
        .map_err(|error| format_compose_error("pull", &error))?;
    ensure_required_ports_available(&runtime_dir)?;
    let start_output = run_docker_compose(&runtime_dir, &["up", "-d", "--remove-orphans"])
        .map_err(|error| format_compose_error("start", &error))?;
    wait_for_runtime_health(&runtime_dir)?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(
            &join_outputs(&engine_output.stdout, &pull_output.stdout),
            &start_output.stdout,
        ),
        stderr: join_outputs(
            &join_outputs(&engine_output.stderr, &pull_output.stderr),
            &start_output.stderr,
        ),
    })
}

pub fn logs<R: Runtime>(
    app: &AppHandle<R>,
    service: Option<String>,
    tail: Option<u16>,
) -> Result<String, String> {
    let runtime_dir = runtime_dir(app)?;
    if !compose_file(&runtime_dir).exists() || !env_file(&runtime_dir).exists() {
        return Err("Local AX BI runtime has not been prepared".to_string());
    }

    let mut args = vec![
        "logs".to_string(),
        "--no-color".to_string(),
        "--tail".to_string(),
        tail_lines(tail).to_string(),
    ];
    if let Some(service_name) = service {
        let service_name = validate_log_service(&service_name)?;
        args.push(service_name.to_string());
    }

    let output = run_docker_compose_owned(&runtime_dir, args)?;
    Ok(join_outputs(&output.stdout, &output.stderr))
}

pub fn credentials<R: Runtime>(app: &AppHandle<R>) -> Result<LocalAdminCredentials, String> {
    let env_file = env_file(&runtime_dir(app)?);
    let password = read_env_value(&env_file, "ADMIN_PASSWORD")?
        .filter(|value| !value.is_empty())
        .ok_or_else(|| {
            "Local admin credentials are not available; prepare the runtime first".to_string()
        })?;

    Ok(LocalAdminCredentials {
        username: AXBI_ADMIN_USERNAME.to_string(),
        password,
    })
}

pub fn complete_admin_onboarding<R: Runtime>(app: &AppHandle<R>) -> Result<(), String> {
    let runtime_dir = runtime_dir(app)?;
    let env_path = env_file(&runtime_dir);
    let password_present = read_env_value(&env_path, "ADMIN_PASSWORD")?
        .map(|value| !value.is_empty())
        .unwrap_or(false);
    if !password_present {
        return Err(
            "Local admin credentials are not available; prepare the runtime first".to_string(),
        );
    }

    fs::write(onboarding_complete_file(&runtime_dir), "complete\n")
        .map_err(|error| format!("Failed to save local admin onboarding state: {error}"))
}

fn ensure_runtime_files<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    let runtime_dir = runtime_dir(app)?;
    fs::create_dir_all(&runtime_dir)
        .map_err(|error| format!("Failed to create local runtime directory: {error}"))?;

    let compose_path = compose_file(&runtime_dir);
    let env_path = env_file(&runtime_dir);
    sync_runtime_files(&compose_path, &env_path)?;

    Ok(runtime_dir)
}

fn sync_runtime_files(compose_path: &Path, env_path: &Path) -> Result<(), String> {
    fs::write(compose_path, LOCAL_COMPOSE_YAML)
        .map_err(|error| format!("Failed to write local Compose file: {error}"))?;

    if !env_path.exists() {
        fs::write(env_path, build_env_file()?)
            .map_err(|error| format!("Failed to write local runtime environment: {error}"))?;
    } else {
        ensure_runtime_secret(env_path)?;
        ensure_colima_profile(env_path, compose_path)?;
    }

    Ok(())
}

fn runtime_dir<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|path| path.join(LOCAL_RUNTIME_DIR))
        .map_err(|error| format!("Failed to resolve app data directory: {error}"))
}

fn compose_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_COMPOSE_FILE)
}

fn env_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_ENV_FILE)
}

fn onboarding_complete_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_ONBOARDING_COMPLETE_FILE)
}

fn build_env_file() -> Result<String, String> {
    Ok(format!(
        r#"COMPOSE_PROJECT_NAME={AXBI_COMPOSE_PROJECT}

AX_BI_SECRET_KEY={}
DATABASE_PASSWORD={}
ADMIN_PASSWORD={}
COLIMA_PROFILE={AXBI_COLIMA_PROFILE}

AXBI_IMAGE=ghcr.io/defai-digital/ax-bi:latest
AX_SERVICES_IMAGE=ghcr.io/defai-digital/ax-bi-services:latest
POSTGRES_IMAGE=pgvector/pgvector:pg18

AXBI_PORT=31423
MCP_PORT=31421
AX_SERVICES_PORT=31424

DATABASE_DB=axbi
DATABASE_USER=axbi
DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_DIALECT=postgresql
POSTGRES_DB=axbi
POSTGRES_USER=axbi

UPLOAD_FOLDER=/app/axbi_home/uploads
LOCAL_DB_NAME=Local Files
LOCAL_DB_PATH=/app/axbi_home/uploads/local_files.duckdb

AXBI_LOAD_EXAMPLES=no
AXBI_LOG_LEVEL=info
ENABLE_PROXY_FIX=true
TALISMAN_ENABLED=false

GENAI_SEMANTIC_INDEX=false
GENAI_SEMANTIC_INDEX_PGVECTOR=false
AI_SEMANTIC_EMBEDDING_PROVIDER=ax_engine_http
AI_SEMANTIC_EMBEDDING_ENDPOINT=http://host.docker.internal:8099/embed
AI_SEMANTIC_EMBEDDING_MODEL=Qwen/Qwen3-Embedding-0.6B
AI_SEMANTIC_EMBEDDING_DIMENSIONS=1024
AI_SEMANTIC_EMBEDDING_TIMEOUT=120

MCP_DEV_USERNAME={AXBI_ADMIN_USERNAME}
MCP_AUTH_ENABLED=false
MCP_JWT_ISSUER=
MCP_JWT_AUDIENCE=
MCP_JWKS_URI=
MCP_REQUIRED_SCOPES=
"#,
        random_hex(48)?,
        random_hex(32)?,
        random_hex(18)?,
    ))
}

fn ensure_runtime_secret(path: &Path) -> Result<(), String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    if let Some(updated) = ensure_runtime_secret_content(&content)? {
        fs::write(path, updated)
            .map_err(|error| format!("Failed to update local runtime environment: {error}"))?;
    }
    Ok(())
}

fn ensure_runtime_secret_content(content: &str) -> Result<Option<String>, String> {
    if read_env_value_from_str(content, "AX_BI_SECRET_KEY").is_some() {
        return Ok(None);
    }

    let mut updated = content.trim_end().to_string();
    if !updated.is_empty() {
        updated.push('\n');
    }
    updated.push_str(&format!("AX_BI_SECRET_KEY={}\n", random_hex(48)?));
    Ok(Some(updated))
}

fn ensure_colima_profile(env_path: &Path, compose_path: &Path) -> Result<(), String> {
    if !cfg!(target_os = "macos")
        || read_env_value(env_path, COLIMA_PROFILE_ENV)?
            .filter(|profile| valid_colima_profile(profile))
            .is_some()
    {
        return Ok(());
    }

    let runtime_dir = compose_path.parent().unwrap_or_else(|| Path::new("."));
    // Legacy Desktop releases used Colima's default profile. New environments
    // write `ax-bi` into .env immediately, so a missing key is an upgrade case.
    let profile = if colima_profile_has_managed_axbi(AXBI_COLIMA_PROFILE, runtime_dir) {
        AXBI_COLIMA_PROFILE
    } else {
        "default"
    };
    let mut content = fs::read_to_string(env_path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    if !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(&format!("{COLIMA_PROFILE_ENV}={profile}\n"));
    fs::write(env_path, content)
        .map_err(|error| format!("Failed to save the local Colima profile: {error}"))
}

fn configured_colima_profile(env_path: &Path) -> String {
    read_env_value(env_path, COLIMA_PROFILE_ENV)
        .ok()
        .flatten()
        .filter(|profile| valid_colima_profile(profile))
        .unwrap_or_else(|| AXBI_COLIMA_PROFILE.to_string())
}

fn valid_colima_profile(profile: &str) -> bool {
    !profile.is_empty()
        && profile
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '-' | '_'))
}

fn colima_profile_has_managed_axbi(profile: &str, runtime_dir: &Path) -> bool {
    let Ok(host) = docker_host(profile) else {
        return false;
    };
    if !docker_daemon_ready(&host) {
        return false;
    }

    let project_filter = format!("label=com.docker.compose.project={AXBI_COMPOSE_PROJECT}");
    let service_filter = "label=com.docker.compose.service=ax-bi";
    let runtime_filter = format!(
        "label=com.docker.compose.project.working_dir={}",
        path_to_string(runtime_dir)
    );
    run_command(
        "docker",
        &[
            "ps",
            "--all",
            "--filter",
            &project_filter,
            "--filter",
            service_filter,
            "--filter",
            &runtime_filter,
            "--format",
            "{{.ID}}",
        ],
        None,
        &[("DOCKER_HOST", &host)],
    )
    .map(|output| !output.stdout.trim().is_empty())
    .unwrap_or(false)
}

fn random_hex(byte_count: usize) -> Result<String, String> {
    let mut bytes = vec![0; byte_count];
    getrandom::fill(&mut bytes)
        .map_err(|error| format!("Failed to read secure random source: {error}"))?;
    Ok(bytes
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<Vec<_>>()
        .join(""))
}

fn dependencies() -> Vec<LocalRuntimeDependency> {
    match RuntimeEngine::current() {
        RuntimeEngine::Colima => vec![
            dependency("Colima", "colima", &["--version"], "brew install colima"),
            dependency("Lima", "limactl", &["--version"], "brew install lima"),
            dependency(
                "Docker CLI",
                "docker",
                &["--version"],
                "brew install docker",
            ),
            dependency(
                "Docker Compose",
                "docker",
                &["compose", "version"],
                "brew install docker-compose",
            ),
        ],
        RuntimeEngine::Docker => vec![
            dependency(
                "Docker CLI",
                "docker",
                &["--version"],
                docker_install_hint(),
            ),
            dependency(
                "Docker Compose",
                "docker",
                &["compose", "version"],
                docker_install_hint(),
            ),
        ],
    }
}

fn docker_install_hint() -> &'static str {
    if cfg!(target_os = "windows") {
        "Install Docker Desktop from https://docs.docker.com/desktop/setup/install/windows-install/ and ensure it is running"
    } else if cfg!(target_os = "macos") {
        "brew install docker docker-compose"
    } else {
        "Install Docker Engine and the Compose plugin for your distribution"
    }
}

fn platform_id() -> &'static str {
    if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "windows") {
        "windows"
    } else {
        "linux"
    }
}

fn platform_label() -> &'static str {
    if cfg!(target_os = "macos") {
        "macOS"
    } else if cfg!(target_os = "windows") {
        "Windows"
    } else {
        "Linux"
    }
}

/// Fail fast with install hints when CLI tools are missing (before starting engines).
fn ensure_cli_dependencies() -> Result<(), String> {
    let missing: Vec<LocalRuntimeDependency> = dependencies()
        .into_iter()
        .filter(|dependency| !dependency.installed)
        .collect();
    if missing.is_empty() {
        return Ok(());
    }

    let details = missing
        .iter()
        .map(|dependency| format!("- {}: {}", dependency.name, dependency.install_hint))
        .collect::<Vec<_>>()
        .join("\n");

    Err(format!(
        "Cannot start local AX BI Docker on {} — missing tools:\n{}\n\n\
         Run locally uses the same AX BI Compose stack on macOS and Windows \
         (Colima on Mac, Docker Desktop on Windows).",
        platform_label(),
        details
    ))
}

fn format_compose_error(action: &str, error: &str) -> String {
    format!(
        "Failed to {action} the local AX BI Docker stack on {}.\n\
         Engine: {} ({})\n\
         {}\n\n\
         Tips:\n\
         - macOS: brew install colima lima docker docker-compose && ensure Colima can start\n\
         - Windows: install/start Docker Desktop, then retry Run locally\n\
         - Confirm `docker compose version` works in a terminal",
        platform_label(),
        RuntimeEngine::current().label(),
        RuntimeEngine::current().name(),
        error.trim()
    )
}

fn dependency(
    name: &str,
    command: &str,
    args: &[&str],
    install_hint: &str,
) -> LocalRuntimeDependency {
    match run_command(command, args, None, &[]) {
        Ok(output) => LocalRuntimeDependency {
            name: name.to_string(),
            command: if args.is_empty() {
                command.to_string()
            } else {
                format!("{command} {}", args.join(" "))
            },
            resolved_path: path_to_string(&resolve_program(command)),
            installed: true,
            version: first_line(&join_outputs(&output.stdout, &output.stderr)),
            install_hint: install_hint.to_string(),
        },
        Err(_) => LocalRuntimeDependency {
            name: name.to_string(),
            command: command.to_string(),
            resolved_path: path_to_string(&resolve_program(command)),
            installed: false,
            version: None,
            install_hint: install_hint.to_string(),
        },
    }
}

fn first_line(value: &str) -> Option<String> {
    value.lines().next().map(str::trim).and_then(|line| {
        if line.is_empty() {
            None
        } else {
            Some(line.to_string())
        }
    })
}

/// Ensure the platform container engine is running.
fn ensure_engine(runtime_dir: &Path) -> Result<CommandOutput, String> {
    match RuntimeEngine::current() {
        RuntimeEngine::Colima => {
            run_colima_start(&configured_colima_profile(&env_file(runtime_dir)))
        }
        RuntimeEngine::Docker => ensure_docker_engine(runtime_dir),
    }
}

fn engine_is_running(colima_profile: &str) -> bool {
    match RuntimeEngine::current() {
        RuntimeEngine::Colima => {
            command_succeeds("colima", &["status", "--profile", colima_profile])
        }
        RuntimeEngine::Docker => docker_host(colima_profile)
            .map(|host| docker_daemon_ready(&host))
            .unwrap_or(false),
    }
}

fn run_colima_start(profile: &str) -> Result<CommandOutput, String> {
    // Explicit limactl check gives a clearer error than Colima's PATH fatality.
    let limactl = resolve_program("limactl");
    if !limactl.is_file() {
        return Err("Lima (limactl) was not found. Colima requires Lima.\n\
             Install with: brew install lima colima\n\
             If already installed, ensure /opt/homebrew/bin is available."
            .to_string());
    }

    let mut prior_output = CommandOutput {
        stdout: String::new(),
        stderr: String::new(),
    };
    if command_succeeds("colima", &["status", "--profile", profile]) {
        if colima_resources_sufficient(profile) {
            return Ok(CommandOutput {
                stdout: format!(
                    "Colima profile {profile} is already running with sufficient resources"
                ),
                stderr: String::new(),
            });
        }
        prior_output = run_command("colima", &["stop", "--profile", profile], None, &[])?;
    }

    let start_output = run_command(
        "colima",
        &[
            "start",
            "--profile",
            profile,
            "--runtime",
            "docker",
            "--cpu",
            AXBI_COLIMA_CPUS,
            "--memory",
            AXBI_COLIMA_MEMORY_GB,
            "--activate=false",
        ],
        None,
        &[],
    )?;
    Ok(CommandOutput {
        stdout: join_outputs(&prior_output.stdout, &start_output.stdout),
        stderr: join_outputs(&prior_output.stderr, &start_output.stderr),
    })
}

fn colima_resources_sufficient(profile: &str) -> bool {
    #[derive(Deserialize)]
    struct ColimaStatus {
        cpu: u64,
        memory: u64,
    }

    let Ok(output) = run_command(
        "colima",
        &["status", "--profile", profile, "--json"],
        None,
        &[],
    ) else {
        return false;
    };
    let Ok(status) = serde_json::from_str::<ColimaStatus>(&output.stdout) else {
        return false;
    };
    let required_cpu = AXBI_COLIMA_CPUS.parse::<u64>().unwrap_or(4);
    let required_memory = AXBI_COLIMA_MEMORY_GB.parse::<u64>().unwrap_or(8) * 1024 * 1024 * 1024;
    status.cpu >= required_cpu && status.memory >= required_memory
}

fn ensure_docker_engine(runtime_dir: &Path) -> Result<CommandOutput, String> {
    let docker_host = docker_host(&configured_colima_profile(&env_file(runtime_dir)))?;
    if docker_daemon_ready(&docker_host) {
        return Ok(CommandOutput {
            stdout: format!(
                "Docker engine already running on {} ({docker_host})",
                platform_label()
            ),
            stderr: String::new(),
        });
    }

    // Launch Docker Desktop when the CLI exists but the daemon is down.
    if let Some(desktop) = docker_desktop_app_path() {
        log::info!("Starting Docker Desktop at {}", desktop.display());
        let mut command = Command::new(&desktop);
        configure_subprocess(&mut command);
        command.spawn().map_err(|error| {
            format!(
                "Docker Engine is not running and Docker Desktop failed to start: {error}\n{}",
                docker_install_hint()
            )
        })?;

        if wait_for_docker_daemon(&docker_host, DOCKER_ENGINE_WAIT)? {
            return Ok(CommandOutput {
                stdout: format!(
                    "Started Docker Desktop on {} and waited for the engine",
                    platform_label()
                ),
                stderr: String::new(),
            });
        }

        return Err(format!(
            "Docker Desktop was launched on {} but the engine did not become ready in time.\n\
             Open Docker Desktop, wait until it reports Running, then try Run locally again.\n\
             Expected Docker host: {docker_host}",
            platform_label()
        ));
    }

    Err(format!(
        "Docker Engine is not available on {}.\n{}",
        platform_label(),
        docker_install_hint()
    ))
}

fn wait_for_docker_daemon(docker_host: &str, timeout: Duration) -> Result<bool, String> {
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        if docker_daemon_ready(docker_host) {
            return Ok(true);
        }
        thread::sleep(DOCKER_ENGINE_POLL);
    }
    Ok(false)
}

fn docker_daemon_ready(docker_host: &str) -> bool {
    let envs = docker_host_envs(docker_host);
    let env_refs: Vec<(&str, &str)> = envs.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    run_command("docker", &["info"], None, &env_refs).is_ok()
}

fn run_docker_compose(runtime_dir: &Path, compose_args: &[&str]) -> Result<CommandOutput, String> {
    run_docker_compose_owned(
        runtime_dir,
        compose_args.iter().map(ToString::to_string).collect(),
    )
}

fn run_docker_compose_owned(
    runtime_dir: &Path,
    compose_args: Vec<String>,
) -> Result<CommandOutput, String> {
    let compose_path = compose_file(runtime_dir);
    let env_path = env_file(runtime_dir);
    let mut args = vec![
        "compose".to_string(),
        "--project-name".to_string(),
        AXBI_COMPOSE_PROJECT.to_string(),
        "--env-file".to_string(),
        path_to_string(&env_path),
        "-f".to_string(),
        path_to_string(&compose_path),
    ];
    args.extend(compose_args);
    let docker_host = docker_host(&configured_colima_profile(&env_file(runtime_dir)))?;
    let envs = docker_host_envs(&docker_host);
    let env_refs: Vec<(&str, &str)> = envs.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    run_command("docker", &arg_refs, Some(runtime_dir), &env_refs)
}

fn compose_services_running(runtime_dir: &Path) -> Result<bool, String> {
    if !compose_file(runtime_dir).exists() || !env_file(runtime_dir).exists() {
        return Ok(false);
    }
    let output = run_docker_compose_owned(
        runtime_dir,
        vec![
            "ps".to_string(),
            "--status".to_string(),
            "running".to_string(),
            "--services".to_string(),
        ],
    )?;

    Ok(output.stdout.lines().any(|line| line.trim() == "ax-bi"))
}

fn wait_for_runtime_health(runtime_dir: &Path) -> Result<(), String> {
    let deadline = Instant::now() + STARTUP_HEALTH_RECONCILE_WAIT;
    let mut last_ps = String::new();
    let urls = runtime_urls(&env_file(runtime_dir));

    while Instant::now() < deadline {
        if compose_services_running(runtime_dir).unwrap_or(false)
            && local_http_healthcheck(urls.web_port)
        {
            return Ok(());
        }

        if let Ok(output) = run_docker_compose(runtime_dir, &["ps"]) {
            last_ps = join_outputs(&output.stdout, &output.stderr);
        }
        thread::sleep(STARTUP_HEALTH_RECONCILE_POLL);
    }

    Err(format!(
        "AX BI containers started, but the web app did not become healthy within {} seconds.{}",
        STARTUP_HEALTH_RECONCILE_WAIT.as_secs(),
        format_output("compose ps", &last_ps)
    ))
}

fn local_runtime_ports(urls: &RuntimeUrls) -> Vec<LocalRuntimePort> {
    vec![
        local_runtime_port("AX BI web", urls.web_port, &urls.web_url, true),
        local_runtime_port("MCP", urls.mcp_port, &urls.mcp_url, false),
        local_runtime_port("AX services", urls.services_port, &urls.services_url, false),
    ]
}

fn local_runtime_port(
    name: &str,
    port: u16,
    url: &str,
    check_axbi_health: bool,
) -> LocalRuntimePort {
    let open = tcp_port_open(port);
    let occupied_by_axbi = if check_axbi_health {
        open && local_http_healthcheck(port)
    } else {
        false
    };

    LocalRuntimePort {
        name: name.to_string(),
        port,
        url: url.to_string(),
        available: !open || occupied_by_axbi,
        occupied_by_axbi,
    }
}

fn ensure_required_ports_available(runtime_dir: &Path) -> Result<(), String> {
    if compose_services_running(runtime_dir).unwrap_or(false) {
        return Ok(());
    }

    let urls = runtime_urls(&env_file(runtime_dir));
    let blocked: Vec<LocalRuntimePort> = local_runtime_ports(&urls)
        .into_iter()
        .filter(|port| !port.available)
        .collect();
    if blocked.is_empty() {
        return Ok(());
    }

    let details = blocked
        .iter()
        .map(|port| format!("- {} port {} ({})", port.name, port.port, port.url))
        .collect::<Vec<_>>()
        .join("\n");
    Err(format!(
        "Cannot start local AX BI because required port(s) are already in use:\n{}\n\n\
         Stop the other service or change the AX BI ports in the local runtime settings.",
        details
    ))
}

fn tcp_port_open(port: u16) -> bool {
    tcp_socket_addr(port)
        .and_then(|addr| TcpStream::connect_timeout(&addr, Duration::from_millis(250)).ok())
        .is_some()
}

fn tcp_socket_addr(port: u16) -> Option<SocketAddr> {
    (AXBI_HEALTH_HOST, port)
        .to_socket_addrs()
        .ok()
        .and_then(|mut addresses| addresses.next())
}

fn runtime_urls(env_path: &Path) -> RuntimeUrls {
    let web_port = read_env_port(env_path, "AXBI_PORT", AXBI_HEALTH_PORT);
    let mcp_port = read_env_port(env_path, "MCP_PORT", AXBI_MCP_PORT);
    let services_port = read_env_port(env_path, "AX_SERVICES_PORT", AXBI_SERVICES_PORT);

    RuntimeUrls {
        web_port,
        mcp_port,
        services_port,
        web_url: format!("http://127.0.0.1:{web_port}/ax-bi/welcome/"),
        mcp_url: format!("http://127.0.0.1:{mcp_port}/mcp"),
        services_url: format!("http://127.0.0.1:{services_port}"),
    }
}

fn read_env_port(env_path: &Path, key: &str, default: u16) -> u16 {
    read_env_value(env_path, key)
        .ok()
        .flatten()
        .and_then(|value| value.parse::<u16>().ok())
        .unwrap_or(default)
}

fn command_succeeds(program: &str, args: &[&str]) -> bool {
    run_command(program, args, None, &[]).is_ok()
}

fn run_command(
    program: &str,
    args: &[&str],
    cwd: Option<&Path>,
    envs: &[(&str, &str)],
) -> Result<CommandOutput, String> {
    let program_path = resolve_program(program);
    let mut command = Command::new(&program_path);
    command.args(args.iter().map(OsStr::new));
    if let Some(cwd) = cwd {
        command.current_dir(cwd);
    }
    configure_subprocess(&mut command);
    apply_env_pairs(&mut command, envs);

    let output = command.output().map_err(|error| {
        format!(
            "Failed to run {program} (resolved as {}): {error}",
            program_path.display()
        )
    })?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    if !output.status.success() {
        return Err(format!(
            "{program} exited with status {}{}{}",
            output.status,
            format_output("stdout", &stdout),
            format_output("stderr", &stderr)
        ));
    }

    Ok(CommandOutput { stdout, stderr })
}

/// Shared subprocess setup for GUI apps: fixed PATH + no console flash on Windows.
fn configure_subprocess(command: &mut Command) {
    apply_augmented_path(command);
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        // CREATE_NO_WINDOW — avoid flashing consoles when spawning docker/colima.
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }
}

fn apply_env_pairs(command: &mut Command, envs: &[(&str, &str)]) {
    for (key, value) in envs {
        if *key == "DOCKER_HOST" && value.is_empty() {
            command.env_remove("DOCKER_HOST");
        } else {
            command.env(key, value);
        }
    }
}

/// Resolve Homebrew / Docker Desktop binaries for GUI-launched applications.
///
/// Finder, Dock, and Windows shortcuts do not inherit the user's interactive
/// shell PATH, so known install prefixes are checked before PATH lookup.
fn resolve_program(program: &str) -> PathBuf {
    for dir in known_bin_dirs() {
        let candidate = dir.join(program_filename(program));
        if candidate.is_file() {
            return candidate;
        }
    }

    if let Some(from_path) = which_on_augmented_path(program) {
        return from_path;
    }

    PathBuf::from(program_filename(program))
}

fn program_filename(program: &str) -> String {
    if cfg!(target_os = "windows") && !program.ends_with(".exe") {
        format!("{program}.exe")
    } else {
        program.to_string()
    }
}

fn which_on_augmented_path(program: &str) -> Option<PathBuf> {
    let name = program_filename(program);
    let path_var = augmented_path();
    for dir in std::env::split_paths(&path_var) {
        let candidate = dir.join(&name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

fn known_bin_dirs() -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    #[cfg(target_os = "macos")]
    {
        dirs.push(PathBuf::from("/opt/homebrew/bin"));
        dirs.push(PathBuf::from("/opt/homebrew/sbin"));
        dirs.push(PathBuf::from("/usr/local/bin"));
        dirs.push(PathBuf::from("/usr/local/sbin"));
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(program_files) = std::env::var("ProgramFiles") {
            dirs.push(
                PathBuf::from(&program_files)
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
            // Newer Docker Desktop installs also expose CLI next to the app.
            dirs.push(PathBuf::from(&program_files).join("Docker").join("Docker"));
            dirs.push(
                PathBuf::from(&program_files)
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("cli-plugins"),
            );
        }
        if let Ok(program_files_x86) = std::env::var("ProgramFiles(x86)") {
            dirs.push(
                PathBuf::from(program_files_x86)
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
        }
        if let Ok(local_app_data) = std::env::var("LOCALAPPDATA") {
            dirs.push(
                PathBuf::from(&local_app_data)
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
            dirs.push(
                PathBuf::from(local_app_data)
                    .join("Programs")
                    .join("Docker")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
        }
        // User PATH often includes this after Docker Desktop install.
        if let Ok(user_profile) = std::env::var("USERPROFILE") {
            dirs.push(
                PathBuf::from(user_profile)
                    .join("AppData")
                    .join("Local")
                    .join("Docker")
                    .join("resources")
                    .join("bin"),
            );
        }
    }

    #[cfg(target_os = "linux")]
    {
        dirs.push(PathBuf::from("/usr/local/bin"));
        dirs.push(PathBuf::from("/usr/bin"));
        if let Ok(home) = std::env::var("HOME") {
            dirs.push(PathBuf::from(home).join(".local").join("bin"));
        }
    }

    dirs
}

/// PATH that includes known install prefixes so child tools (e.g. Colima → limactl)
/// resolve correctly when the desktop app is launched without a login shell.
fn augmented_path() -> String {
    let mut parts: Vec<PathBuf> = known_bin_dirs();
    if let Some(existing) = std::env::var_os("PATH") {
        parts.extend(std::env::split_paths(&existing));
    }
    // Deduplicate while preserving order.
    let mut seen = std::collections::HashSet::new();
    parts.retain(|p| seen.insert(p.clone()));
    std::env::join_paths(parts)
        .map(|os| os.to_string_lossy().into_owned())
        .unwrap_or_else(|_| std::env::var("PATH").unwrap_or_default())
}

fn apply_augmented_path(command: &mut Command) {
    command.env("PATH", augmented_path());
}

fn format_output(label: &str, value: &str) -> String {
    if value.trim().is_empty() {
        String::new()
    } else {
        format!("\n{label}:\n{}", value.trim())
    }
}

fn docker_host(colima_profile: &str) -> Result<String, String> {
    match RuntimeEngine::current() {
        RuntimeEngine::Colima => {
            let home = home_dir()?;
            Ok(format!(
                "unix://{}/.colima/{colima_profile}/docker.sock",
                path_to_string(&home)
            ))
        }
        // Pin the local engine endpoint so a stale inherited DOCKER_HOST cannot break us.
        RuntimeEngine::Docker => {
            if cfg!(target_os = "windows") {
                Ok("npipe:////./pipe/docker_engine".to_string())
            } else {
                Ok("unix:///var/run/docker.sock".to_string())
            }
        }
    }
}

fn docker_host_envs(docker_host: &str) -> Vec<(String, String)> {
    // Always set DOCKER_HOST for managed runtime commands (including platform default).
    vec![("DOCKER_HOST".to_string(), docker_host.to_string())]
}

fn home_dir() -> Result<PathBuf, String> {
    if let Ok(home) = std::env::var("HOME") {
        return Ok(PathBuf::from(home));
    }
    #[cfg(target_os = "windows")]
    if let Ok(profile) = std::env::var("USERPROFILE") {
        return Ok(PathBuf::from(profile));
    }
    Err("Home directory is not set (HOME / USERPROFILE)".to_string())
}

/// Path to Docker Desktop app when installed (Windows; optional macOS fallback).
fn docker_desktop_app_path() -> Option<PathBuf> {
    let mut candidates = Vec::new();

    #[cfg(target_os = "windows")]
    {
        if let Ok(program_files) = std::env::var("ProgramFiles") {
            candidates.push(
                PathBuf::from(program_files)
                    .join("Docker")
                    .join("Docker")
                    .join("Docker Desktop.exe"),
            );
        }
        if let Ok(program_files_x86) = std::env::var("ProgramFiles(x86)") {
            candidates.push(
                PathBuf::from(program_files_x86)
                    .join("Docker")
                    .join("Docker")
                    .join("Docker Desktop.exe"),
            );
        }
        if let Ok(local_app_data) = std::env::var("LOCALAPPDATA") {
            candidates.push(
                PathBuf::from(local_app_data)
                    .join("Docker")
                    .join("Docker Desktop.exe"),
            );
        }
    }

    #[cfg(target_os = "macos")]
    {
        candidates.push(PathBuf::from(
            "/Applications/Docker.app/Contents/MacOS/Docker",
        ));
    }

    candidates.into_iter().find(|path| path.is_file())
}

fn local_http_healthcheck(port: u16) -> bool {
    let Ok(mut addresses) = (AXBI_HEALTH_HOST, port).to_socket_addrs() else {
        return false;
    };
    let Some(address) = addresses.next() else {
        return false;
    };
    let Ok(mut stream) = TcpStream::connect_timeout(&address, Duration::from_millis(750)) else {
        return false;
    };
    let _ = stream.set_read_timeout(Some(Duration::from_millis(750)));
    let _ = stream.set_write_timeout(Some(Duration::from_millis(750)));

    if stream
        .write_all(b"GET /health HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n")
        .is_err()
    {
        return false;
    }

    let mut response = String::new();
    stream.read_to_string(&mut response).is_ok()
        && (response.starts_with("HTTP/1.1 200") || response.starts_with("HTTP/1.0 200"))
}

fn validate_log_service(service: &str) -> Result<&str, String> {
    let service = service.trim();
    if ALLOWED_LOG_SERVICES.contains(&service) {
        Ok(service)
    } else {
        Err("Unknown local AX BI service name".to_string())
    }
}

fn tail_lines(value: Option<u16>) -> u16 {
    value.unwrap_or(200).clamp(1, MAX_LOG_TAIL_LINES)
}

fn read_env_value(path: &Path, key: &str) -> Result<Option<String>, String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    Ok(read_env_value_from_str(&content, key))
}

fn read_env_value_from_str(content: &str, key: &str) -> Option<String> {
    content.lines().find_map(|line| {
        let (line_key, line_value) = line.split_once('=')?;
        if line_key.trim() == key {
            Some(line_value.trim().to_string())
        } else {
            None
        }
    })
}

fn join_outputs(first: &str, second: &str) -> String {
    match (first.trim(), second.trim()) {
        ("", "") => String::new(),
        (first, "") => first.to_string(),
        ("", second) => second.to_string(),
        (first, second) => format!("{first}\n{second}"),
    }
}

fn path_to_string(path: &Path) -> String {
    path.to_string_lossy().to_string()
}

#[cfg(test)]
mod tests {
    use super::{
        augmented_path, build_env_file, configured_colima_profile, docker_host,
        ensure_runtime_secret_content, platform_id, platform_label, program_filename,
        read_env_value_from_str, resolve_program, runtime_urls, tail_lines, valid_colima_profile,
        validate_log_service, RuntimeEngine, AXBI_ADMIN_USERNAME, AXBI_COLIMA_CPUS,
        AXBI_COLIMA_MEMORY_GB, AXBI_COLIMA_PROFILE, LOCAL_COMPOSE_YAML, MAX_LOG_TAIL_LINES,
    };
    use std::fs;
    use std::path::Path;

    #[test]
    fn generated_compose_binds_public_services_to_loopback() {
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${AXBI_PORT:-31423}:31423"));
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${MCP_PORT:-31421}:31421"));
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${AX_SERVICES_PORT:-31424}:31424"));
        assert!(LOCAL_COMPOSE_YAML.contains("TALISMAN_ENABLED: ${TALISMAN_ENABLED:-false}"));
    }

    #[test]
    fn generated_env_contains_required_secrets() {
        let env_file = build_env_file().unwrap();

        assert!(read_env_value_from_str(&env_file, "AX_BI_SECRET_KEY").is_some());
        assert!(read_env_value_from_str(&env_file, "DATABASE_PASSWORD").is_some());
        let admin_password = read_env_value_from_str(&env_file, "ADMIN_PASSWORD").unwrap();
        assert_eq!(admin_password.len(), 36);
        assert_ne!(admin_password, "admin");
        assert_eq!(
            read_env_value_from_str(&env_file, "COLIMA_PROFILE").unwrap(),
            AXBI_COLIMA_PROFILE
        );
        assert_eq!(
            read_env_value_from_str(&env_file, "TALISMAN_ENABLED").unwrap(),
            "false"
        );
        assert_eq!(
            read_env_value_from_str(&env_file, "MCP_DEV_USERNAME").unwrap(),
            AXBI_ADMIN_USERNAME
        );
    }

    #[test]
    fn generated_colima_start_uses_recommended_resources() {
        assert_eq!(AXBI_COLIMA_CPUS, "4");
        assert_eq!(AXBI_COLIMA_MEMORY_GB, "8");
    }

    #[test]
    fn configured_colima_profile_accepts_safe_names_and_rejects_paths() {
        let env_path =
            std::env::temp_dir().join(format!("axbi-profile-test-{}.env", std::process::id()));
        fs::write(&env_path, "COLIMA_PROFILE=default\n").unwrap();
        assert_eq!(configured_colima_profile(&env_path), "default");

        fs::write(&env_path, "COLIMA_PROFILE=../../other\n").unwrap();
        assert_eq!(configured_colima_profile(&env_path), AXBI_COLIMA_PROFILE);
        let _ = fs::remove_file(&env_path);

        assert!(valid_colima_profile("team_ax-bi"));
        assert!(!valid_colima_profile(""));
        assert!(!valid_colima_profile("../ax-bi"));
    }

    #[test]
    fn runtime_urls_default_to_standard_ports_when_env_missing() {
        let urls = runtime_urls(Path::new("/definitely/missing/.env"));

        assert_eq!(urls.web_port, 31423);
        assert_eq!(urls.mcp_port, 31421);
        assert_eq!(urls.services_port, 31424);
        assert_eq!(urls.web_url, "http://127.0.0.1:31423/ax-bi/welcome/");
    }

    #[test]
    fn runtime_urls_follow_env_port_overrides() {
        let env_path =
            std::env::temp_dir().join(format!("axbi-runtime-test-{}.env", std::process::id()));
        fs::write(
            &env_path,
            "AXBI_PORT=18088\nMCP_PORT=15008\nAX_SERVICES_PORT=15010\n",
        )
        .unwrap();

        let urls = runtime_urls(&env_path);
        let _ = fs::remove_file(&env_path);

        assert_eq!(urls.web_port, 18088);
        assert_eq!(urls.mcp_url, "http://127.0.0.1:15008/mcp");
        assert_eq!(urls.services_url, "http://127.0.0.1:15010");
    }

    #[test]
    fn adds_missing_runtime_secret() {
        let env_file = "COMPOSE_PROJECT_NAME=axbi\nADMIN_PASSWORD=admin\n";
        let updated = ensure_runtime_secret_content(env_file).unwrap().unwrap();

        assert!(read_env_value_from_str(&updated, "AX_BI_SECRET_KEY").is_some());
        assert_eq!(
            read_env_value_from_str(&updated, "ADMIN_PASSWORD").unwrap(),
            "admin"
        );
    }

    #[test]
    fn log_services_are_allowlisted() {
        assert_eq!(validate_log_service("ax-bi").unwrap(), "ax-bi");
        assert!(validate_log_service("../../../etc/passwd").is_err());
        assert!(validate_log_service("unknown").is_err());
    }

    #[test]
    fn log_tail_is_clamped() {
        assert_eq!(tail_lines(None), 200);
        assert_eq!(tail_lines(Some(0)), 1);
        assert_eq!(tail_lines(Some(1_000)), MAX_LOG_TAIL_LINES);
    }

    #[test]
    fn leaves_relative_program_names_available_for_path_resolution() {
        assert_eq!(
            resolve_program("command-not-on-path"),
            Path::new(&program_filename("command-not-on-path"))
        );
    }

    #[test]
    fn augmented_path_includes_known_prefixes_on_macos() {
        let path = augmented_path();
        if cfg!(target_os = "macos") {
            assert!(
                path.contains("/opt/homebrew/bin") || path.contains("/usr/local/bin"),
                "expected Homebrew prefix in PATH, got: {path}"
            );
        }
    }

    #[test]
    fn docker_host_matches_platform_engine() {
        let host = docker_host(AXBI_COLIMA_PROFILE).unwrap();
        match RuntimeEngine::current() {
            RuntimeEngine::Colima => {
                assert!(host.contains(AXBI_COLIMA_PROFILE));
                assert!(host.starts_with("unix://"));
            }
            RuntimeEngine::Docker => {
                if cfg!(target_os = "windows") {
                    assert_eq!(host, "npipe:////./pipe/docker_engine");
                } else {
                    assert_eq!(host, "unix:///var/run/docker.sock");
                }
            }
        }
    }

    #[test]
    fn engine_is_colima_only_on_macos() {
        if cfg!(target_os = "macos") {
            assert_eq!(RuntimeEngine::current(), RuntimeEngine::Colima);
            assert_eq!(RuntimeEngine::current().label(), "Colima");
        } else {
            assert_eq!(RuntimeEngine::current(), RuntimeEngine::Docker);
            assert_eq!(RuntimeEngine::current().label(), "Docker Engine");
        }
    }

    #[test]
    fn both_desktop_platforms_support_local_runtime() {
        // Local AX BI Docker is a first-class path on every desktop OS we ship.
        assert!(matches!(
            RuntimeEngine::current(),
            RuntimeEngine::Colima | RuntimeEngine::Docker
        ));
        assert!(!platform_id().is_empty());
        assert!(!platform_label().is_empty());
    }
}
