// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use serde::{Deserialize, Serialize};
use std::ffi::OsStr;
use std::fs;
use std::io::{Read, Write};
use std::net::{TcpStream, ToSocketAddrs};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Duration;
use tauri::{AppHandle, Manager, Runtime};

const AXBI_COLIMA_PROFILE: &str = "ax-bi";
const AXBI_COMPOSE_PROJECT: &str = "axbi";
const AXBI_ADMIN_USERNAME: &str = "admin";
const AXBI_WEB_URL: &str = "http://127.0.0.1:8088/ax-bi/welcome/";
const AXBI_HEALTH_HOST: &str = "127.0.0.1";
const AXBI_HEALTH_PORT: u16 = 8088;
const AXBI_MCP_URL: &str = "http://127.0.0.1:5008/mcp";
const AXBI_SERVICES_URL: &str = "http://127.0.0.1:5010";
const LOCAL_RUNTIME_DIR: &str = "local-runtime";
const LOCAL_ENV_FILE: &str = ".env";
const LOCAL_COMPOSE_FILE: &str = "docker-compose.yml";
const MAX_LOG_TAIL_LINES: u16 = 500;

const ALLOWED_LOG_SERVICES: &[&str] = &[
    "redis",
    "db",
    "superset-init",
    "superset",
    "superset-worker",
    "superset-worker-beat",
    "mcp",
    "ax-services",
];

const LOCAL_COMPOSE_YAML: &str = r#"# Generated by AX BI Desktop.
# This file is managed by the desktop local runtime manager.

x-axbi-image: &axbi-image ${AXBI_IMAGE:-ghcr.io/defai-digital/ax-bi:latest}
x-axbi-services-image: &axbi-services-image ${AX_SERVICES_IMAGE:-ghcr.io/defai-digital/ax-bi-services:latest}

x-axbi-env: &axbi-env
  SUPERSET_CONFIG_PATH: /app/docker/pythonpath_axbi/superset_config.py
  SUPERSET_ENV: production
  SUPERSET_LOAD_EXAMPLES: ${SUPERSET_LOAD_EXAMPLES:-no}
  SUPERSET_LOG_LEVEL: ${SUPERSET_LOG_LEVEL:-info}
  SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:?Set SUPERSET_SECRET_KEY in .env}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD in .env}
  DATABASE_DIALECT: ${DATABASE_DIALECT:-postgresql}
  DATABASE_HOST: ${DATABASE_HOST:-db}
  DATABASE_PORT: ${DATABASE_PORT:-5432}
  DATABASE_DB: ${DATABASE_DB:-superset}
  DATABASE_USER: ${DATABASE_USER:-superset}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:?Set DATABASE_PASSWORD in .env}
  UPLOAD_FOLDER: ${UPLOAD_FOLDER:-/app/superset_home/uploads}
  LOCAL_DB_NAME: ${LOCAL_DB_NAME:-Local Files}
  LOCAL_DB_PATH: ${LOCAL_DB_PATH:-/app/superset_home/uploads/local_files.duckdb}
  REDIS_HOST: redis
  REDIS_PORT: 6379
  ENABLE_PROXY_FIX: ${ENABLE_PROXY_FIX:-true}
  MCP_AUTH_ENABLED: ${MCP_AUTH_ENABLED:-false}
  MCP_DEV_USERNAME: ${MCP_DEV_USERNAME:-admin}
  MCP_JWT_ISSUER: ${MCP_JWT_ISSUER:-}
  MCP_JWT_AUDIENCE: ${MCP_JWT_AUDIENCE:-}
  MCP_JWKS_URI: ${MCP_JWKS_URI:-}
  MCP_REQUIRED_SCOPES: ${MCP_REQUIRED_SCOPES:-}
  GENAI_SEMANTIC_INDEX: ${GENAI_SEMANTIC_INDEX:-false}
  GENAI_SEMANTIC_INDEX_PGVECTOR: ${GENAI_SEMANTIC_INDEX_PGVECTOR:-false}
  AI_SEMANTIC_EMBEDDING_PROVIDER: ${AI_SEMANTIC_EMBEDDING_PROVIDER:-ax_engine_http}
  AI_SEMANTIC_EMBEDDING_ENDPOINT: ${AI_SEMANTIC_EMBEDDING_ENDPOINT:-http://host.docker.internal:8099/embed}
  AI_SEMANTIC_EMBEDDING_MODEL: ${AI_SEMANTIC_EMBEDDING_MODEL:-Qwen/Qwen3-Embedding-0.6B}
  AI_SEMANTIC_EMBEDDING_DIMENSIONS: ${AI_SEMANTIC_EMBEDDING_DIMENSIONS:-1024}

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg18}
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB:-superset}
      POSTGRES_USER: ${POSTGRES_USER:-superset}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?Set DATABASE_PASSWORD in .env}
    volumes:
      - db_home:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-superset} -d ${POSTGRES_DB:-superset}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  superset-init:
    image: *axbi-image
    command: ["/app/docker/docker-init.sh"]
    environment: *axbi-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

  superset:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SUPERSET_PORT:-8088}:8088"
    environment: *axbi-env
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset_home:/app/superset_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "/app/docker/docker-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  superset-worker:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: unless-stopped
    environment: *axbi-env
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset_home:/app/superset_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  superset-worker-beat:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: unless-stopped
    environment: *axbi-env
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

  mcp:
    image: *axbi-image
    command: ["/app/docker/docker-bootstrap.sh", "mcp"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MCP_PORT:-5008}:5008"
    environment:
      <<: *axbi-env
      MCP_PORT: 5008
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset_home:/app/superset_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import socket; socket.create_connection(('127.0.0.1', 5008), 5).close()",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  ax-services:
    image: *axbi-services-image
    restart: unless-stopped
    environment:
      AX_SERVICES_HOST: 0.0.0.0
      AX_SERVICES_PORT: 5010
      AX_SUPERSET_BASE_URL: http://superset:8088
      AX_SERVICES_LOG_LEVEL: ${AX_SERVICES_LOG_LEVEL:-info}
    ports:
      - "127.0.0.1:${AX_SERVICES_PORT:-5010}:5010"
    depends_on:
      superset:
        condition: service_healthy

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeDependency {
    pub name: String,
    pub command: String,
    pub installed: bool,
    pub version: Option<String>,
    pub install_hint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeStatus {
    pub runtime_dir: String,
    pub compose_file: String,
    pub env_file: String,
    pub configured: bool,
    pub dependencies: Vec<LocalRuntimeDependency>,
    pub colima_profile: String,
    pub colima_running: bool,
    pub docker_host: String,
    pub docker_ready: bool,
    pub axbi_running: bool,
    pub axbi_healthy: bool,
    pub web_url: String,
    pub mcp_url: String,
    pub services_url: String,
    pub admin_username: String,
    pub admin_password_present: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalRuntimeCommandOutput {
    pub status: LocalRuntimeStatus,
    pub stdout: String,
    pub stderr: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalAdminCredentials {
    pub username: String,
    pub password: String,
}

#[derive(Debug)]
struct CommandOutput {
    stdout: String,
    stderr: String,
}

pub fn status<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeStatus, String> {
    let runtime_dir = runtime_dir(app)?;
    let compose_file = compose_file(&runtime_dir);
    let env_file = env_file(&runtime_dir);
    let dependencies = dependencies();
    let configured = compose_file.exists() && env_file.exists();
    let colima_running = command_succeeds("colima", ["status", "--profile", AXBI_COLIMA_PROFILE]);
    let docker_host = docker_host()?;
    let docker_ready =
        command_succeeds_with_env("docker", ["info"], &[("DOCKER_HOST", &docker_host)]);
    let axbi_running = docker_ready && compose_services_running(&runtime_dir)?;
    let axbi_healthy = axbi_running && local_http_healthcheck();
    let admin_password_present = configured
        && read_env_value(&env_file, "ADMIN_PASSWORD")
            .ok()
            .flatten()
            .map(|password| !password.is_empty())
            .unwrap_or(false);

    Ok(LocalRuntimeStatus {
        runtime_dir: path_to_string(&runtime_dir),
        compose_file: path_to_string(&compose_file),
        env_file: path_to_string(&env_file),
        configured,
        dependencies,
        colima_profile: AXBI_COLIMA_PROFILE.to_string(),
        colima_running,
        docker_host,
        docker_ready,
        axbi_running,
        axbi_healthy,
        web_url: AXBI_WEB_URL.to_string(),
        mcp_url: AXBI_MCP_URL.to_string(),
        services_url: AXBI_SERVICES_URL.to_string(),
        admin_username: AXBI_ADMIN_USERNAME.to_string(),
        admin_password_present,
    })
}

pub fn prepare<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeStatus, String> {
    ensure_runtime_files(app)?;
    status(app)
}

pub fn start<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    run_colima_start()?;
    let output = run_docker_compose(&runtime_dir, ["up", "-d"])?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: output.stdout,
        stderr: output.stderr,
    })
}

pub fn stop<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    let output = run_docker_compose(&runtime_dir, ["stop"])?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: output.stdout,
        stderr: output.stderr,
    })
}

pub fn restart<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    run_colima_start()?;
    let stop_output = run_docker_compose(&runtime_dir, ["stop"])?;
    let start_output = run_docker_compose(&runtime_dir, ["up", "-d"])?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(&stop_output.stdout, &start_output.stdout),
        stderr: join_outputs(&stop_output.stderr, &start_output.stderr),
    })
}

pub fn update<R: Runtime>(app: &AppHandle<R>) -> Result<LocalRuntimeCommandOutput, String> {
    let runtime_dir = ensure_runtime_files(app)?;
    run_colima_start()?;
    let pull_output = run_docker_compose(&runtime_dir, ["pull"])?;
    let start_output = run_docker_compose(&runtime_dir, ["up", "-d"])?;

    Ok(LocalRuntimeCommandOutput {
        status: status(app)?,
        stdout: join_outputs(&pull_output.stdout, &start_output.stdout),
        stderr: join_outputs(&pull_output.stderr, &start_output.stderr),
    })
}

pub fn logs<R: Runtime>(
    app: &AppHandle<R>,
    service: Option<String>,
    tail: Option<u16>,
) -> Result<String, String> {
    let runtime_dir = runtime_dir(app)?;
    if !compose_file(&runtime_dir).exists() || !env_file(&runtime_dir).exists() {
        return Err("Local AX BI runtime has not been prepared".to_string());
    }

    let mut args = vec![
        "logs".to_string(),
        "--no-color".to_string(),
        "--tail".to_string(),
        tail_lines(tail).to_string(),
    ];
    if let Some(service_name) = service {
        let service_name = validate_log_service(&service_name)?;
        args.push(service_name.to_string());
    }

    let output = run_docker_compose_owned(&runtime_dir, args)?;
    Ok(join_outputs(&output.stdout, &output.stderr))
}

pub fn credentials<R: Runtime>(app: &AppHandle<R>) -> Result<LocalAdminCredentials, String> {
    let env_file = env_file(&runtime_dir(app)?);
    let password = read_env_value(&env_file, "ADMIN_PASSWORD")?
        .ok_or_else(|| "Local AX BI admin password has not been generated".to_string())?;

    Ok(LocalAdminCredentials {
        username: AXBI_ADMIN_USERNAME.to_string(),
        password,
    })
}

fn ensure_runtime_files<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    let runtime_dir = runtime_dir(app)?;
    fs::create_dir_all(&runtime_dir)
        .map_err(|error| format!("Failed to create local runtime directory: {error}"))?;

    let compose_path = compose_file(&runtime_dir);
    fs::write(compose_path, LOCAL_COMPOSE_YAML)
        .map_err(|error| format!("Failed to write local Compose file: {error}"))?;

    let env_path = env_file(&runtime_dir);
    if !env_path.exists() {
        fs::write(env_path, build_env_file()?)
            .map_err(|error| format!("Failed to write local runtime environment: {error}"))?;
    }

    Ok(runtime_dir)
}

fn runtime_dir<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|path| path.join(LOCAL_RUNTIME_DIR))
        .map_err(|error| format!("Failed to resolve app data directory: {error}"))
}

fn compose_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_COMPOSE_FILE)
}

fn env_file(runtime_dir: &Path) -> PathBuf {
    runtime_dir.join(LOCAL_ENV_FILE)
}

fn build_env_file() -> Result<String, String> {
    Ok(format!(
        r#"COMPOSE_PROJECT_NAME={AXBI_COMPOSE_PROJECT}

SUPERSET_SECRET_KEY={}
DATABASE_PASSWORD={}
ADMIN_PASSWORD={}

AXBI_IMAGE=ghcr.io/defai-digital/ax-bi:latest
AX_SERVICES_IMAGE=ghcr.io/defai-digital/ax-bi-services:latest
POSTGRES_IMAGE=pgvector/pgvector:pg18

SUPERSET_PORT=8088
MCP_PORT=5008
AX_SERVICES_PORT=5010

DATABASE_DB=superset
DATABASE_USER=superset
DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_DIALECT=postgresql
POSTGRES_DB=superset
POSTGRES_USER=superset

UPLOAD_FOLDER=/app/superset_home/uploads
LOCAL_DB_NAME=Local Files
LOCAL_DB_PATH=/app/superset_home/uploads/local_files.duckdb

SUPERSET_LOAD_EXAMPLES=no
SUPERSET_LOG_LEVEL=info
ENABLE_PROXY_FIX=true

GENAI_SEMANTIC_INDEX=false
GENAI_SEMANTIC_INDEX_PGVECTOR=false
AI_SEMANTIC_EMBEDDING_PROVIDER=ax_engine_http
AI_SEMANTIC_EMBEDDING_ENDPOINT=http://host.docker.internal:8099/embed
AI_SEMANTIC_EMBEDDING_MODEL=Qwen/Qwen3-Embedding-0.6B
AI_SEMANTIC_EMBEDDING_DIMENSIONS=1024
AI_SEMANTIC_EMBEDDING_TIMEOUT=120

MCP_DEV_USERNAME=admin
MCP_AUTH_ENABLED=false
MCP_JWT_ISSUER=
MCP_JWT_AUDIENCE=
MCP_JWKS_URI=
MCP_REQUIRED_SCOPES=
"#,
        random_hex(48)?,
        random_hex(32)?,
        random_hex(18)?
    ))
}

fn random_hex(byte_count: usize) -> Result<String, String> {
    let mut bytes = vec![0; byte_count];
    getrandom::fill(&mut bytes)
        .map_err(|error| format!("Failed to read secure random source: {error}"))?;
    Ok(bytes
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<Vec<_>>()
        .join(""))
}

fn dependencies() -> Vec<LocalRuntimeDependency> {
    vec![
        dependency("Colima", "colima", ["--version"], "brew install colima"),
        dependency("Docker CLI", "docker", ["--version"], "brew install docker"),
        dependency(
            "Docker Compose",
            "docker compose",
            ["compose", "version"],
            "brew install docker-compose",
        ),
    ]
}

fn dependency<const N: usize>(
    name: &str,
    command: &str,
    args: [&str; N],
    install_hint: &str,
) -> LocalRuntimeDependency {
    match run_command(
        command.split_whitespace().next().unwrap_or(command),
        args,
        None,
        &[],
    ) {
        Ok(output) => LocalRuntimeDependency {
            name: name.to_string(),
            command: command.to_string(),
            installed: true,
            version: first_line(&join_outputs(&output.stdout, &output.stderr)),
            install_hint: install_hint.to_string(),
        },
        Err(_) => LocalRuntimeDependency {
            name: name.to_string(),
            command: command.to_string(),
            installed: false,
            version: None,
            install_hint: install_hint.to_string(),
        },
    }
}

fn first_line(value: &str) -> Option<String> {
    value.lines().next().map(str::trim).and_then(|line| {
        if line.is_empty() {
            None
        } else {
            Some(line.to_string())
        }
    })
}

fn run_colima_start() -> Result<CommandOutput, String> {
    run_command(
        "colima",
        [
            "start",
            "--profile",
            AXBI_COLIMA_PROFILE,
            "--runtime",
            "docker",
            "--activate=false",
        ],
        None,
        &[],
    )
}

fn run_docker_compose<const N: usize>(
    runtime_dir: &Path,
    compose_args: [&str; N],
) -> Result<CommandOutput, String> {
    run_docker_compose_owned(
        runtime_dir,
        compose_args.iter().map(ToString::to_string).collect(),
    )
}

fn run_docker_compose_owned(
    runtime_dir: &Path,
    compose_args: Vec<String>,
) -> Result<CommandOutput, String> {
    let compose_path = compose_file(runtime_dir);
    let env_path = env_file(runtime_dir);
    let mut args = vec![
        "compose".to_string(),
        "--project-name".to_string(),
        AXBI_COMPOSE_PROJECT.to_string(),
        "--env-file".to_string(),
        path_to_string(&env_path),
        "-f".to_string(),
        path_to_string(&compose_path),
    ];
    args.extend(compose_args);
    let docker_host = docker_host()?;
    run_command_owned(
        "docker",
        args,
        Some(runtime_dir),
        &[("DOCKER_HOST", docker_host.as_str())],
    )
}

fn compose_services_running(runtime_dir: &Path) -> Result<bool, String> {
    if !compose_file(runtime_dir).exists() || !env_file(runtime_dir).exists() {
        return Ok(false);
    }
    let output = run_docker_compose_owned(
        runtime_dir,
        vec![
            "ps".to_string(),
            "--status".to_string(),
            "running".to_string(),
            "--services".to_string(),
        ],
    )?;

    Ok(output.stdout.lines().any(|line| line.trim() == "superset"))
}

fn command_succeeds<const N: usize>(program: &str, args: [&str; N]) -> bool {
    run_command(program, args, None, &[]).is_ok()
}

fn command_succeeds_with_env<const N: usize>(
    program: &str,
    args: [&str; N],
    envs: &[(&str, &str)],
) -> bool {
    run_command(program, args, None, envs).is_ok()
}

fn run_command<const N: usize>(
    program: &str,
    args: [&str; N],
    cwd: Option<&Path>,
    envs: &[(&str, &str)],
) -> Result<CommandOutput, String> {
    run_command_owned(
        program,
        args.iter().map(ToString::to_string).collect(),
        cwd,
        envs,
    )
}

fn run_command_owned(
    program: &str,
    args: Vec<String>,
    cwd: Option<&Path>,
    envs: &[(&str, &str)],
) -> Result<CommandOutput, String> {
    let mut command = Command::new(program);
    command.args(args.iter().map(OsStr::new));
    if let Some(cwd) = cwd {
        command.current_dir(cwd);
    }
    for (key, value) in envs {
        command.env(key, value);
    }

    let output = command
        .output()
        .map_err(|error| format!("Failed to run {program}: {error}"))?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    if !output.status.success() {
        return Err(format!(
            "{program} exited with status {}{}{}",
            output.status,
            format_output("stdout", &stdout),
            format_output("stderr", &stderr)
        ));
    }

    Ok(CommandOutput { stdout, stderr })
}

fn format_output(label: &str, value: &str) -> String {
    if value.trim().is_empty() {
        String::new()
    } else {
        format!("\n{label}:\n{}", value.trim())
    }
}

fn docker_host() -> Result<String, String> {
    let home = std::env::var("HOME").map_err(|_| "HOME is not set".to_string())?;
    Ok(format!(
        "unix://{home}/.colima/{AXBI_COLIMA_PROFILE}/docker.sock"
    ))
}

fn local_http_healthcheck() -> bool {
    let Ok(mut addresses) = (AXBI_HEALTH_HOST, AXBI_HEALTH_PORT).to_socket_addrs() else {
        return false;
    };
    let Some(address) = addresses.next() else {
        return false;
    };
    let Ok(mut stream) = TcpStream::connect_timeout(&address, Duration::from_millis(750)) else {
        return false;
    };
    let _ = stream.set_read_timeout(Some(Duration::from_millis(750)));
    let _ = stream.set_write_timeout(Some(Duration::from_millis(750)));

    if stream
        .write_all(b"GET /health HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n")
        .is_err()
    {
        return false;
    }

    let mut response = String::new();
    stream.read_to_string(&mut response).is_ok()
        && (response.starts_with("HTTP/1.1 200") || response.starts_with("HTTP/1.0 200"))
}

fn validate_log_service(service: &str) -> Result<&str, String> {
    let service = service.trim();
    if ALLOWED_LOG_SERVICES.contains(&service) {
        Ok(service)
    } else {
        Err("Unknown local AX BI service name".to_string())
    }
}

fn tail_lines(value: Option<u16>) -> u16 {
    value.unwrap_or(200).clamp(1, MAX_LOG_TAIL_LINES)
}

fn read_env_value(path: &Path, key: &str) -> Result<Option<String>, String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("Failed to read local runtime environment: {error}"))?;
    Ok(read_env_value_from_str(&content, key))
}

fn read_env_value_from_str(content: &str, key: &str) -> Option<String> {
    content.lines().find_map(|line| {
        let (line_key, line_value) = line.split_once('=')?;
        if line_key.trim() == key {
            Some(line_value.trim().to_string())
        } else {
            None
        }
    })
}

fn join_outputs(first: &str, second: &str) -> String {
    match (first.trim(), second.trim()) {
        ("", "") => String::new(),
        (first, "") => first.to_string(),
        ("", second) => second.to_string(),
        (first, second) => format!("{first}\n{second}"),
    }
}

fn path_to_string(path: &Path) -> String {
    path.to_string_lossy().to_string()
}

#[cfg(test)]
mod tests {
    use super::{
        build_env_file, read_env_value_from_str, tail_lines, validate_log_service,
        LOCAL_COMPOSE_YAML, MAX_LOG_TAIL_LINES,
    };

    #[test]
    fn generated_compose_binds_public_services_to_loopback() {
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${SUPERSET_PORT:-8088}:8088"));
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${MCP_PORT:-5008}:5008"));
        assert!(LOCAL_COMPOSE_YAML.contains("127.0.0.1:${AX_SERVICES_PORT:-5010}:5010"));
    }

    #[test]
    fn generated_env_contains_required_secrets() {
        let env_file = build_env_file().unwrap();

        assert!(read_env_value_from_str(&env_file, "SUPERSET_SECRET_KEY").is_some());
        assert!(read_env_value_from_str(&env_file, "DATABASE_PASSWORD").is_some());
        assert!(read_env_value_from_str(&env_file, "ADMIN_PASSWORD").is_some());
        assert_eq!(
            read_env_value_from_str(&env_file, "MCP_DEV_USERNAME").unwrap(),
            "admin"
        );
    }

    #[test]
    fn log_services_are_allowlisted() {
        assert_eq!(validate_log_service("superset").unwrap(), "superset");
        assert!(validate_log_service("../../../etc/passwd").is_err());
        assert!(validate_log_service("unknown").is_err());
    }

    #[test]
    fn log_tail_is_clamped() {
        assert_eq!(tail_lines(None), 200);
        assert_eq!(tail_lines(Some(0)), 1);
        assert_eq!(tail_lines(Some(1_000)), MAX_LOG_TAIL_LINES);
    }
}
