---
blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/defai-digital/ax-bi/discussions/new?category=ideas
    about: Propose a feature request to the AxBI community
  - name: Q&A
    url: https://github.com/defai-digital/ax-bi/discussions/new?category=q-a-help
    about: Open a community Q&A thread on GitHub Discussions
  - name: Slack
    url:  https://bit.ly/join-axbi-slack
    about: Join the AxBI Community on Slack for other discussions and assistance
